import { AnnotatedSamples } from "@/components/platform/AnnotatedSamples";

export default function SamplesPage() {
  return <main className="mx-auto max-w-7xl px-6 py-10"><p className="text-sm font-semibold uppercase tracking-widest text-teal-700">Composer-generated evidence</p><h1 className="mt-2 text-3xl font-semibold">Annotated Synthetic Samples</h1><p className="mt-3 max-w-3xl leading-7 text-slate-600">Every supported target message has at least one sample generated by its deterministic production composer and linked line-by-line to Tag Intelligence.</p><div className="mt-8"><AnnotatedSamples /></div></main>;
}
