"""The generic Network Validated Rule templates, read against an invented flat guide.

MT 998 below is not a SWIFT message and none of its rules is a SWIFT rule; the layout
imitates a Message Reference Guide closely enough for the reader (cover, sections, Format
Specifications table, Field Specifications) so each sentence shape can be proven to
translate — exactly, weaker than stated, or refused with its reason — on a machine that
holds no licensed document.
"""

from __future__ import annotations

from collections.abc import Iterator

import pytest

from app.rule_engine.dsl import AllEqual, AllOf, AtMostOne, ForEachOccurrence, Implies, Predicate
from app.rule_engine.mt_mrg.corpus import read_guide_text
from app.rule_engine.mt_mrg.document import classify, identify, pages_of
from app.rule_engine.mt_mrg.formatspec import StructureBuilder
from app.rule_engine.mt_mrg.rules import MrgSourceRule, RuleFidelity, UnsupportedReason
from app.rule_engine.mt_mrg.templates import translate
from app.rule_engine.sources import normalise

COVER = """[[PAGE 1]]
Standards
Standards MT November 2026
Message Reference Guide
MT 998 Synthetic Flat Fixture (Not A Swift Document)
This file is an invented fixture owned by this repository. It imitates the layout of a
Message Reference Guide so the reader can be tested without a licensed document.
Published by SWIFT and generated by MyStandards.
[[PAGE 2]]
MT 998 Synthetic Flat Fixture (Not A Swift Document)
MT 998 Scope
An invented flat message with a repetitive group. It settles nothing.
MT 998 Format Specifications
MT 998 Synthetic Flat Fixture (Not A Swift Document)
Status Tag Field Name Content/Options No.
M 20 Sender's Reference 16x 1
O 21 Related Reference 16x 2
M 32A Value Date/Currency/Amount 6!n3!a15d 3
O 33B Currency/Instructed Amount 3!a15d 4
O 36 Exchange Rate 12d 5
O 23E Instruction Code 4!c[/30x] 6
O 50a Ordering Customer A, F, K 7
---->
M 61 Statement Line 6!n3!a15d 8
O 86 Information 6*65x 9
----|
O 71A Details of Charges 3!a 10
O 72 Sender to Receiver Information 6*35x 11
M = Mandatory, O = Optional
MT 998 Network Validated Rules
{rules}
MT 998 Usage Rules
None.
MT 998 Field Specifications
1. Field 20: Sender's Reference
FORMAT
16x (Reference)
PRESENCE
Mandatory
DEFINITION
A reference.
2. Field 21: Related Reference
FORMAT
16x (Reference)
PRESENCE
Optional
DEFINITION
A reference.
3. Field 32A: Value Date/Currency/Amount
FORMAT
Option A 6!n3!a15d (Date)(Currency)(Amount)
PRESENCE
Mandatory
DEFINITION
An amount.
4. Field 33B: Currency/Instructed Amount
FORMAT
Option B 3!a15d (Currency)(Amount)
PRESENCE
Optional
DEFINITION
An amount.
5. Field 36: Exchange Rate
FORMAT
12d (Rate)
PRESENCE
Conditional (see rule C1)
DEFINITION
A rate.
6. Field 23E: Instruction Code
FORMAT
Option E 4!c[/30x] (Instruction Code)(Additional Information)
PRESENCE
Optional
DEFINITION
A code.
CODES
SDVA Same Day Value
TELB Telephone Beneficiary
7. Field 50a: Ordering Customer
FORMAT
Option A [/34x] (Account)
4!a2!a2!c[3!c] (Identifier Code)
Option F 35x (Party Identifier)
4*(1!n/33x) (Number/Name and Address)
Option K [/34x] (Account)
4*35x (Name and Address)
PRESENCE
Optional
DEFINITION
A party.
8. Field 61: Statement Line
FORMAT
6!n3!a15d (Date)(Currency)(Amount)
PRESENCE
Mandatory
DEFINITION
A line.
9. Field 86: Information
FORMAT
6*65x (Narrative)
PRESENCE
Optional
DEFINITION
Narrative.
10. Field 71A: Details of Charges
FORMAT
3!a (Code)
PRESENCE
Optional
DEFINITION
A code.
CODES
BEN Beneficiary
OUR Our
SHA Shared
11. Field 72: Sender to Receiver Information
FORMAT
6*35x (Narrative)
PRESENCE
Optional
DEFINITION
Narrative.
"""


def guide_with(*rules: str) -> str:
    numbered = "\n".join(f"C{index} {text}" for index, text in enumerate(rules, start=1))
    return COVER.replace("{rules}", numbered)


def translations(*rules: str) -> Iterator[tuple[MrgSourceRule, object]]:
    text = normalise(guide_with(*rules))
    pages = pages_of(text)
    identity, problems = identify(pages)
    assert identity is not None, problems
    spans = classify(pages, identity.message_type)
    structure = StructureBuilder(identity.message_type, identity.standards_release).build(
        pages, spans, message_name=identity.message_name, release_text=identity.release_cover_text
    )
    from app.rule_engine.mt_mrg.rules import discover

    found = discover(
        pages,
        spans,
        message_type=identity.message_type,
        message_name=identity.message_name,
        standards_release=identity.standards_release,
        release_text=identity.release_cover_text,
    )
    assert len(found) == len(rules)
    for rule in found:
        yield rule, translate(rule, structure)


def one(rule_text: str):  # type: ignore[no-untyped-def]
    [(_, translation)] = list(translations(rule_text))
    return translation


def test_the_flat_fixture_reads_as_a_guide_with_a_root_and_a_repetitive_group() -> None:
    evidence = read_guide_text(
        guide_with("If field 21 is present, field 72 must also be present (Error code(s): Z01)."),
        source_checksum="0" * 64,
    )
    assert evidence.message_type == "MT998"
    assert evidence.sequences == 1  # the 61/86 repetitive group
    assert evidence.rows == 11
    assert [rule["disposition"] for rule in evidence.rules] == ["EXACT"]


def test_conditional_presence_in_a_flat_message_is_exact() -> None:
    translation = one("If field 21 is present, field 72 must also be present (Error code(s): Z01).")
    assert translation.fidelity is RuleFidelity.EXACT
    assert translation.template == "CONDITIONAL_PRESENCE_GENERAL"
    assert isinstance(translation.assertion, Implies)


def test_otherwise_clause_adds_the_reverse_implication() -> None:
    translation = one(
        "If field 33B is present, then field 36 is mandatory, otherwise field 36 is not allowed "
        "(Error code(s): Z02)."
    )
    assert translation.fidelity is RuleFidelity.EXACT
    assert isinstance(translation.assertion, AllOf) and len(translation.assertion.all_of) == 2


def test_code_conditions_and_code_restrictions_are_exact() -> None:
    translation = one(
        "If field 71A contains code OUR, field 23E may contain only the codes SDVA or TELB "
        "(Error code(s): Z03)."
    )
    assert translation.fidelity is RuleFidelity.EXACT
    assert isinstance(translation.assertion, Implies)
    consequence = translation.assertion.implies.then
    assert isinstance(consequence, Predicate) and consequence.values == ("SDVA", "TELB")


def test_option_restriction_resolves_to_the_other_option_rows() -> None:
    translation = one(
        "If field 71A contains code BEN, field 50a may be used with option A only "
        "(Error code(s): Z04)."
    )
    assert translation.fidelity is RuleFidelity.EXACT
    consequence = translation.assertion.implies.then  # type: ignore[union-attr]
    assert isinstance(consequence, AllOf) and len(consequence.all_of) == 2  # 50F and 50K absent


def test_currency_difference_condition_extracts_both_components() -> None:
    translation = one(
        "If field 33B is present and the currency code is different from the currency code in "
        "field 32A, field 36 must be present, otherwise field 36 is not allowed "
        "(Error code(s): Z05)."
    )
    assert translation.fidelity is RuleFidelity.EXACT
    assert translation.template == "CURRENCY_DIFFERENCE_CONDITION"
    predicates = [
        item
        for item in [*translation.assertion.all_of[0].implies.if_.all_of]  # type: ignore[union-attr]
        if isinstance(item, Predicate) and item.extract is not None
    ]
    assert predicates and predicates[0].other_extract is not None
    assert predicates[0].other_extract.pattern == r"^\d{6}(?P<value>[A-Z]{3})"


def test_currency_consistency_across_occurrences_is_all_equal() -> None:
    translation = one(
        "The currency code in the amount fields 32A and 61 must be the same for all "
        "occurrences of these fields in the message (Error code(s): Z06)."
    )
    assert translation.fidelity is RuleFidelity.EXACT
    assert isinstance(translation.assertion, AllEqual)
    assert len(translation.assertion.all_equal) == 2


def test_either_or_not_both_is_at_most_one() -> None:
    translation = one(
        "Either field 21 or field 72, but not both, may be present (Error code(s): Z07)."
    )
    assert translation.fidelity is RuleFidelity.EXACT
    assert isinstance(translation.assertion, AtMostOne)


def test_a_count_limit_in_a_repetitive_group_is_scoped_per_occurrence() -> None:
    translation = one(
        "In each occurrence of the repetitive sequence, field 86 cannot appear more than twice "
        "(Error code(s): Z08)."
    )
    assert translation.fidelity is RuleFidelity.EXACT
    assert isinstance(translation.assertion, ForEachOccurrence)


def test_the_repetitive_sequence_count_is_counted_through_its_mandatory_field() -> None:
    translation = one(
        "The repetitive sequence must appear at least twice, but not more than ten times "
        "(Error code(s): Z09)."
    )
    assert translation.fidelity is RuleFidelity.EXACT
    assert translation.template == "SEQUENCE_COUNT"
    assert translation.references[0].tag == "61"


def test_a_dependency_table_becomes_one_implication_per_row() -> None:
    translation = one(
        "The presence of field 72 depends on the value of field 71A as follows (Error code(s): "
        "Z10): if field 71A is ... then field 72 is ... BEN Mandatory OUR Not allowed SHA Optional"
    )
    assert translation.fidelity is RuleFidelity.EXACT
    assert translation.template == "DEPENDENCY_TABLE"
    assert isinstance(translation.assertion, AllOf) and len(translation.assertion.all_of) == 2


def test_envelope_and_arithmetic_rules_are_refused_with_their_reason() -> None:
    envelope = one(
        "If the country codes of the Sender's and the Receiver's BICs are within the list AD, AT, "
        "then field 33B is mandatory (Error code(s): Z11)."
    )
    assert envelope.fidelity is RuleFidelity.UNSUPPORTED
    assert envelope.reason is UnsupportedReason.ENVELOPE_DEPENDENT
    arithmetic = one(
        "The amount in field 32A must equal the sum of the amounts in all occurrences of field 61 "
        "(Error code(s): Z12)."
    )
    assert arithmetic.fidelity is RuleFidelity.UNSUPPORTED
    assert arithmetic.reason is UnsupportedReason.ARITHMETIC_NOT_MODELLED


def test_mandatory_fields_in_optional_sequences_is_enforced_by_structure() -> None:
    translation = one(
        "In all optional sequences, the fields with status M must be present if the sequence "
        "is present, and are otherwise not allowed (Error code(s): Z13)."
    )
    assert translation.fidelity is RuleFidelity.EXACT
    assert "ENFORCED_BY_STRUCTURE" in translation.residual


def test_an_unknown_sentence_form_keeps_its_disposition() -> None:
    translation = one(
        "The broker identification must be present when sent by a broker (Error code(s): Z14)."
    )
    assert translation.fidelity is RuleFidelity.NOT_RECOGNISED
    assert translation.reason is UnsupportedReason.SENTENCE_FORM_NOT_RECOGNISED


@pytest.mark.parametrize(
    "sentence",
    [
        "If field 21 is present, field 72 must also be present (Error code(s): Z01).",
        "Either field 21 or field 72, but not both, may be present (Error code(s): Z07).",
    ],
)
def test_every_reference_of_an_exact_translation_is_resolved(sentence: str) -> None:
    translation = one(sentence)
    assert translation.references and all(item.resolved for item in translation.references)
