"""What a Message Reference Guide says it is, and which pages hold what.

Both answers come from the document rather than from a caller or a model. The cover page
states the release, the book and the publisher; the section headings state where the
Format Specifications end and the Network Validated Rules begin. A filename is never
trusted — an operator can rename a file, and a wrong message type is exactly the mistake
that would put MT541's settlement-amount rule onto MT540.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from enum import StrEnum

from app.rule_engine.sources import PAGE_MARKER, Segment

#: The publisher line the MyStandards exporter writes on the cover page.
PUBLISHER_LINE = "Published by SWIFT and generated by MyStandards."
#: The cover-page line that names the book.
GUIDE_LINE = "Message Reference Guide"

COVER_RELEASE = re.compile(r"^Standards MT (?P<month>[A-Z][a-z]+) (?P<year>\d{4})$")
#: ``MT 110 Advice of Cheque(s)``, ``MT 752 Authorisation to Pay, Accept or Negotiate`` and the
#: common-group guides ``MT n90 Advice of Charges, …`` (one guide for MT 190, 290 … 990) are all
#: covers SWIFT publishes; the number is three digits or ``n`` plus two digits.
COVER_MESSAGE = re.compile(
    r"^MT (?P<number>\d{3}|n\d{2}) (?P<name>[A-Z][A-Za-z0-9'’ /,&().-]+?)\s*$"
)


#: Release identities this reader understands. A month/year the repository has never
#: modelled is reported rather than mapped to a plausible neighbour.
RELEASE_BY_COVER: dict[tuple[str, str], str] = {
    ("November", "2025"): "SR2025",
    ("November", "2026"): "SR2026",
}


def release_for_cover(month: str, year: str) -> str | None:
    """``Standards MT November 2027`` is SR2027 without a commit.

    SWIFT standards releases go live in November and are named for their year, so the
    table above is a record of what has been seen, not a whitelist. Any other month is
    still reported as RELEASE_NOT_MODELLED: an interim publication is not a release.
    """
    known = RELEASE_BY_COVER.get((month, year))
    if known is not None:
        return known
    if month == "November" and year.isdigit() and 2020 <= int(year) <= 2099:
        return f"SR{year}"
    return None


SECTION_HEADING = re.compile(
    r"^MT (?P<number>\d{3}|n\d{2}) "
    r"(?P<section>Scope|Format Specifications|Network Validated Rules|Usage Rules|"
    r"Field Specifications)$"
)
FIELD_HEADING = re.compile(r"^(?P<ordinal>\d{1,3})\. Field (?P<tag>\d{2}[A-Za-z]?): ")
#: The block labels a Field Specification uses. Upper case and alone on their line, which
#: is what makes them safe to treat as structure rather than as prose that happens to shout.
FIELD_BLOCKS = frozenset(
    {
        "FORMAT",
        "PRESENCE",
        "QUALIFIER",
        "DEFINITION",
        "CODES",
        "NETWORK VALIDATED RULES",
        "USAGE RULES",
        "EXAMPLES",
    }
)


class MrgSection(StrEnum):
    """What a page of the guide is, and therefore what authority it carries."""

    TABLE_OF_CONTENTS = "TABLE_OF_CONTENTS"
    MESSAGE_TYPES = "MESSAGE_TYPES"
    MESSAGE_SCOPE = "MESSAGE_SCOPE"
    FORMAT_SPECIFICATION = "FORMAT_SPECIFICATION"
    NETWORK_VALIDATED_RULE = "NETWORK_VALIDATED_RULE"
    USAGE_RULE = "USAGE_RULE"
    FIELD_SPECIFICATION = "FIELD_SPECIFICATION"
    LEGAL_NOTICE = "LEGAL_NOTICE"
    COVER = "COVER"
    DESCRIPTION_ONLY = "DESCRIPTION_ONLY"


#: Which sections a deterministic rule may be derived from, and which are read-only
#: context. An example is never on this list: an example containing a field says the field
#: is *possible*, never that it is required.
NORMATIVE_SECTIONS = frozenset(
    {
        MrgSection.NETWORK_VALIDATED_RULE,
        MrgSection.FIELD_SPECIFICATION,
    }
)
#: Sections that establish structure rather than a use of it.
STRUCTURAL_SECTIONS = frozenset({MrgSection.FORMAT_SPECIFICATION})


class MrgBlock(StrEnum):
    """A labelled block inside one Field Specification."""

    FORMAT = "FORMAT"
    PRESENCE = "PRESENCE"
    QUALIFIER = "QUALIFIER"
    DEFINITION = "DEFINITION"
    CODES = "CODES"
    NETWORK_VALIDATED_RULES = "NETWORK_VALIDATED_RULES"
    USAGE_RULES = "USAGE_RULES"
    EXAMPLES = "EXAMPLES"


BLOCK_BY_LABEL = {
    "FORMAT": MrgBlock.FORMAT,
    "PRESENCE": MrgBlock.PRESENCE,
    "QUALIFIER": MrgBlock.QUALIFIER,
    "DEFINITION": MrgBlock.DEFINITION,
    "CODES": MrgBlock.CODES,
    "NETWORK VALIDATED RULES": MrgBlock.NETWORK_VALIDATED_RULES,
    "USAGE RULES": MrgBlock.USAGE_RULES,
    "EXAMPLES": MrgBlock.EXAMPLES,
}

#: Blocks whose content is illustrative. Kept so a reviewer can see them; never a rule.
ILLUSTRATIVE_BLOCKS = frozenset({MrgBlock.EXAMPLES, MrgBlock.DEFINITION})


class MrgIdentityProblem(StrEnum):
    NO_COVER_PAGE = "NO_COVER_PAGE"
    NOT_A_MESSAGE_REFERENCE_GUIDE = "NOT_A_MESSAGE_REFERENCE_GUIDE"
    PUBLISHER_NOT_STATED = "PUBLISHER_NOT_STATED"
    RELEASE_NOT_STATED = "RELEASE_NOT_STATED"
    RELEASE_NOT_MODELLED = "RELEASE_NOT_MODELLED"
    MESSAGE_NOT_STATED = "MESSAGE_NOT_STATED"
    SECTIONS_MISSING = "SECTIONS_MISSING"


@dataclass(frozen=True)
class MrgIdentity:
    """What the document says about itself. Every field is quoted, none is inferred."""

    message_type: str
    message_name: str
    standards_release: str
    release_cover_text: str
    guide_title: str
    publisher_statement: str
    page_count: int

    @property
    def logical_source_id(self) -> str:
        """``SWIFT-MT-SR2026-MT541-MRG`` — stable across re-exports of the same book."""
        return f"SWIFT-MT-{self.standards_release}-{self.message_type}-MRG"


@dataclass(frozen=True)
class MrgLine:
    """One line, numbered exactly as ``sources`` numbers it.

    The shared numbering is what lets a section span and a segment be compared without
    either of them re-deriving the other's positions: a page marker consumes no line
    number in either module, so line 4 512 means the same line in both.
    """

    number: int
    text: str
    page: int


@dataclass(frozen=True)
class MrgPage:
    number: int
    lines: tuple[MrgLine, ...]

    @property
    def texts(self) -> tuple[str, ...]:
        return tuple(item.text for item in self.lines)

    @property
    def text(self) -> str:
        return "\n".join(self.texts)


@dataclass(frozen=True)
class MrgSectionSpan:
    section: MrgSection
    heading: str
    first_page: int
    last_page: int
    first_line: int
    last_line: int

    def covers_line(self, line: int) -> bool:
        return self.first_line <= line <= self.last_line


def pages_of(text: str) -> tuple[MrgPage, ...]:
    """Split page-marked extracted text back into numbered pages and lines.

    ``sources.ingest`` writes ``[[PAGE n]]`` markers for a PDF and drops them again when it
    numbers lines, so this reads the same marked text rather than re-opening the document.
    """
    pages: list[MrgPage] = []
    current: list[MrgLine] = []
    number = 0
    line_number = 0
    for raw in text.split("\n"):
        marker = PAGE_MARKER.match(raw)
        if marker:
            if number:
                pages.append(MrgPage(number=number, lines=tuple(current)))
            number = int(marker.group(1))
            current = []
            continue
        line_number += 1
        if number:
            current.append(MrgLine(number=line_number, text=raw, page=number))
    if number:
        pages.append(MrgPage(number=number, lines=tuple(current)))
    return tuple(pages)


def identify(pages: tuple[MrgPage, ...]) -> tuple[MrgIdentity | None, tuple[str, ...]]:
    """Read the cover page. Returns the identity, or the reasons there is none."""
    problems: list[str] = []
    if not pages:
        return None, (MrgIdentityProblem.NO_COVER_PAGE.value,)
    cover = [line.strip() for line in pages[0].texts if line.strip()]

    release_text = next((line for line in cover if COVER_RELEASE.fullmatch(line)), None)
    release = None
    if release_text is None:
        problems.append(MrgIdentityProblem.RELEASE_NOT_STATED.value)
    else:
        match = COVER_RELEASE.fullmatch(release_text)
        assert match is not None  # noqa: S101 - guarded by the search above
        release = release_for_cover(match.group("month"), match.group("year"))
        if release is None:
            problems.append(MrgIdentityProblem.RELEASE_NOT_MODELLED.value)

    if GUIDE_LINE not in cover:
        problems.append(MrgIdentityProblem.NOT_A_MESSAGE_REFERENCE_GUIDE.value)
    publisher = next((line for line in cover if line == PUBLISHER_LINE), None)
    if publisher is None:
        problems.append(MrgIdentityProblem.PUBLISHER_NOT_STATED.value)

    message = None
    for index, line in enumerate(cover):
        candidate = line
        # A long title wraps on the cover: ``…Termination/Re-`` / ``couponing Confirmation``.
        # The wrapped part is the line that follows, hyphen closed or space joined, until
        # the cover's own boilerplate resumes.
        for following in cover[index + 1 : index + 3]:
            # A wrapped title leaves a short remainder; the cover's prose lines are long
            # sentences. Length, not wording, tells them apart.
            if following in {GUIDE_LINE, PUBLISHER_LINE} or len(following) > 45:
                break
            if candidate.endswith("-"):
                candidate = candidate[:-1] + following
            else:
                candidate = f"{candidate} {following}"
        message = COVER_MESSAGE.fullmatch(candidate)
        if message is not None:
            break
    if message is None:
        problems.append(MrgIdentityProblem.MESSAGE_NOT_STATED.value)

    if problems or release is None or message is None or release_text is None:
        return None, tuple(problems)
    return (
        MrgIdentity(
            message_type=f"MT{message.group('number')}",
            message_name=message.group("name").strip(),
            standards_release=release,
            release_cover_text=release_text,
            guide_title=GUIDE_LINE,
            publisher_statement=PUBLISHER_LINE,
            page_count=len(pages),
        ),
        (),
    )


#: Sections every Message Reference Guide this reader accepts must declare.
REQUIRED_SECTIONS = (
    MrgSection.MESSAGE_SCOPE,
    MrgSection.FORMAT_SPECIFICATION,
    MrgSection.NETWORK_VALIDATED_RULE,
    MrgSection.USAGE_RULE,
    MrgSection.FIELD_SPECIFICATION,
)

SECTION_BY_HEADING = {
    "Scope": MrgSection.MESSAGE_SCOPE,
    "Format Specifications": MrgSection.FORMAT_SPECIFICATION,
    "Network Validated Rules": MrgSection.NETWORK_VALIDATED_RULE,
    "Usage Rules": MrgSection.USAGE_RULE,
    "Field Specifications": MrgSection.FIELD_SPECIFICATION,
}


def classify(pages: tuple[MrgPage, ...], message_type: str) -> tuple[MrgSectionSpan, ...]:
    """Where each section starts and ends, taken from the document's own headings.

    A heading is only honoured when it names *this* message. ``MT 540 Scope`` inside the
    MT541 book would be a cross-book contamination, and treating it as this book's scope is
    precisely how one message's rules end up attributed to another.
    """
    number = message_type.removeprefix("MT")
    all_lines = [line for page in pages for line in page.lines]
    if not all_lines:
        return ()
    starts: list[tuple[MrgLine, MrgSection, str]] = []
    for line in all_lines:
        stripped = line.text.strip()
        if stripped == "Table of Contents":
            starts.append((line, MrgSection.TABLE_OF_CONTENTS, stripped))
            continue
        if stripped == "Message Types":
            starts.append((line, MrgSection.MESSAGE_TYPES, stripped))
            continue
        if stripped == "Legal Notices":
            starts.append((line, MrgSection.LEGAL_NOTICE, stripped))
            continue
        heading = SECTION_HEADING.fullmatch(stripped)
        if heading and heading.group("number") == number:
            starts.append((line, SECTION_BY_HEADING[heading.group("section")], stripped))

    # Each section opens once. A heading that reappears is a running repeat — the table of
    # contents restates its own title on every page it covers — and must not restart a
    # section that is already open.
    ordered: list[tuple[MrgLine, MrgSection, str]] = []
    seen: set[MrgSection] = set()
    for entry in starts:
        if entry[1] in seen:
            continue
        seen.add(entry[1])
        ordered.append(entry)

    spans: list[MrgSectionSpan] = []
    if ordered and ordered[0][0].number > all_lines[0].number:
        spans.append(
            MrgSectionSpan(
                section=MrgSection.COVER,
                heading=GUIDE_LINE,
                first_page=pages[0].number,
                last_page=ordered[0][0].page,
                first_line=all_lines[0].number,
                last_line=ordered[0][0].number - 1,
            )
        )
    for position, (line, section, title) in enumerate(ordered):
        if position + 1 < len(ordered):
            following = ordered[position + 1][0]
            last_line = following.number - 1
            last_page = following.page
        else:
            last_line = all_lines[-1].number
            last_page = pages[-1].number
        spans.append(
            MrgSectionSpan(
                section=section,
                heading=title,
                first_page=line.page,
                last_page=max(last_page, line.page),
                first_line=line.number,
                last_line=max(last_line, line.number),
            )
        )
    return tuple(spans)


def missing_sections(spans: tuple[MrgSectionSpan, ...]) -> tuple[MrgSection, ...]:
    present = {span.section for span in spans}
    return tuple(item for item in REQUIRED_SECTIONS if item not in present)


def section_of_line(spans: tuple[MrgSectionSpan, ...], line: int) -> MrgSection:
    """Which section a line belongs to.

    Line-level rather than page-level because two sections routinely share a page: the
    Usage Rules end and the Field Specifications begin on the same sheet, and attributing
    a usage paragraph to the Field Specifications would file evidence under the wrong
    authority.
    """
    for span in spans:
        if span.covers_line(line):
            return span.section
    return MrgSection.DESCRIPTION_ONLY


def section_of_segment(spans: tuple[MrgSectionSpan, ...], segment: Segment) -> MrgSection:
    return section_of_line(spans, segment.line_start)


# --------------------------------------------------------------------------------------
# Reading flowing text out of a two-column, page-broken, hyphenated PDF
# --------------------------------------------------------------------------------------

FOOTER_WITH_TITLE = re.compile(
    r"^(?P<page>\d{1,4})\s+Message Reference Guide - MT (?:\d{3}|n\d{2}) .+$"
)


def body_lines(
    pages: tuple[MrgPage, ...], message_type: str, message_name: str, release_text: str
) -> list[MrgLine]:
    """Every line of the document with the page furniture removed.

    Furniture is identified by *what it is*, never by what it looks like. The Format
    Specifications table numbers its rows in a right-hand column, and a wrapped row leaves
    that number alone on a line — indistinguishable in isolation from a page number at the
    foot of the page. Matching the page's own number, and only at the bottom of that page,
    keeps row 18 of the table from being deleted as the footer of page 18.
    """
    running_header = f"MT {message_type.removeprefix('MT')} {message_name}"
    kept: list[MrgLine] = []
    for page in pages:
        filled = [line for line in page.lines if line.text.strip()]
        for position, line in enumerate(filled):
            stripped = line.text.strip()
            if stripped in {release_text, running_header}:
                continue
            at_foot = position >= len(filled) - 2
            if at_foot and stripped == str(page.number):
                continue
            footer = FOOTER_WITH_TITLE.fullmatch(stripped)
            if footer and footer.group("page") == str(page.number):
                continue
            kept.append(line)
    return kept


def flow(lines: list[str]) -> str:
    """Join wrapped lines into readable text.

    The exporter breaks words at the right margin with an ordinary hyphen, and does so
    inside SWIFT tokens as well as inside prose — ``:22F::DB-`` / ``NM//VEND`` is one
    field reference, not two. Rejoining every hyphenated break therefore repairs the
    tokens the rules are actually about, at the cost of closing up the few genuine
    hyphens that happen to fall on a line end. That trade is deliberate: a rule is read
    from its field references, and no reviewer decision rests on the prose this file
    renders.
    """
    text = "\n".join(lines)
    text = re.sub(r"-\n(?=\S)", "", text)
    return re.sub(r"\n(?=\S)", " ", text)
