"use client";

/**
 * API & Automation — one page, not a developer portal.
 *
 * Everything an automation tester needs to be productive in five minutes: the templates,
 * a live upload, the JSON contract, and working examples they can paste.
 */

import { useEffect, useMemo, useState } from "react";
import { Icon } from "@/components/studio/Icon";
import { Badge, CopyButton, Panel, SegmentedControl } from "@/components/studio/ui";
import { apiUrl } from "@/lib/api-client";
import { studioApi } from "@/lib/studio-api";
import type { StudioCatalogue } from "@/lib/studio-types";

type Language = "curl" | "java" | "python" | "javascript";

const LANGUAGE_LABELS: Record<Language, string> = {
  curl: "curl",
  java: "Java / REST Assured",
  python: "Python",
  javascript: "JavaScript",
};

const ENDPOINTS: Array<{ method: string; path: string; body: string }> = [
  { method: "GET", path: "/api/v1/catalogue", body: "Every message you can generate." },
  {
    method: "GET",
    path: "/api/v1/messages/{messageType}/spec",
    body: "Every field, with presence, format and examples.",
  },
  {
    method: "GET",
    path: "/api/v1/messages/{messageType}/samples",
    body: "Every sample variant this message has.",
  },
  {
    method: "GET",
    path: "/api/v1/messages/{messageType}/samples/{variant}",
    body: "A ready-made valid input set: MINIMAL, TYPICAL or FULL.",
  },
  {
    method: "POST",
    path: "/api/v1/messages/validate",
    body: "Validate without keeping anything.",
  },
  {
    method: "POST",
    path: "/api/v1/messages/generate",
    body: "Tag or element data in, a complete message out.",
  },
  {
    method: "POST",
    path: "/api/v1/messages/import",
    body: "An existing MT or ISO 20022 message in, its canonical values out. The format and the message are read from the message itself.",
  },
  {
    method: "POST",
    path: "/api/v1/messages/diff",
    body: "Regenerate from your values and compare with a message you already have. Every difference is attributed; deterministic, no model involved.",
  },
  {
    method: "POST",
    path: "/api/v1/messages/generate-from-excel",
    body: "Multipart .xlsx upload; one message per ScenarioID.",
  },
  { method: "GET", path: "/api/v1/templates/{MT|MX}.xlsx", body: "The Excel templates." },
  {
    method: "GET",
    path: "/api/v1/intelligence/search?q=",
    body: "Look up any tag or element. Deterministic.",
  },
  {
    method: "GET",
    path: "/api/v1/intelligence/field?id=",
    body: "Everything known about one field.",
  },
  {
    method: "GET",
    path: "/api/v1/messages/recent",
    body: "Recently generated messages.",
  },
  {
    method: "GET",
    path: "/api/v1/messages/id/{id}",
    body: "One message and all of its outputs.",
  },
  {
    method: "GET",
    path: "/api/v1/messages/id/{id}/download/{output}",
    body: "The exact generated bytes, no added formatting.",
  },
  {
    method: "GET",
    path: "/api/v1/messages/id/{id}/evidence.zip",
    body: "Every output plus the validation report.",
  },
  {
    method: "GET",
    path: "/api/v1/coverage",
    body: "What is implemented for every configured message, measured — not declared.",
  },
  {
    method: "GET",
    path: "/api/v1/sources",
    body: "Which authoritative specification artifacts are present, and what each unlocks.",
  },
];

export function Automation() {
  // apiUrl is pure and resolves identically on the server and the client.
  const base = apiUrl("");
  const [language, setLanguage] = useState<Language>("curl");
  const [catalogue, setCatalogue] = useState<StudioCatalogue | null>(null);

  useEffect(() => {
    studioApi.catalogue().then(setCatalogue).catch(() => setCatalogue(null));
  }, []);

  const samples = useMemo(() => buildSamples(base), [base]);

  return (
    <div className="space-y-6">
      <div className="grid gap-4 lg:grid-cols-3">
        <QuickCard
          icon="sheet"
          title="Excel templates"
          body="Generated from the specification, so you never have to invent a tag or an XPath."
        >
          <div className="flex flex-wrap gap-2">
            <a
              href={studioApi.templateUrl("MT")}
              className="inline-flex h-9 items-center gap-1.5 rounded-md border border-line-2 bg-panel px-3 text-[0.8125rem] font-medium transition-colors duration-150 hover:bg-rail"
            >
              <Icon name="download" className="h-4 w-4" />
              MT
            </a>
            <a
              href={studioApi.templateUrl("MX")}
              className="inline-flex h-9 items-center gap-1.5 rounded-md border border-line-2 bg-panel px-3 text-[0.8125rem] font-medium transition-colors duration-150 hover:bg-rail"
            >
              <Icon name="download" className="h-4 w-4" />
              MX
            </a>
          </div>
        </QuickCard>

        <QuickCard
          icon="terminal"
          title="OpenAPI"
          body="The full machine-readable contract, and an interactive console for exploring it."
        >
          <div className="flex flex-wrap gap-2">
            <a
              href={`${base}/docs`}
              target="_blank"
              rel="noreferrer"
              className="inline-flex h-9 items-center gap-1.5 rounded-md border border-line-2 bg-panel px-3 text-[0.8125rem] font-medium transition-colors duration-150 hover:bg-rail"
            >
              Swagger UI
              <Icon name="external" className="h-4 w-4" />
            </a>
            <a
              href={`${base}/openapi.json`}
              target="_blank"
              rel="noreferrer"
              className="inline-flex h-9 items-center gap-1.5 rounded-md border border-line-2 bg-panel px-3 text-[0.8125rem] font-medium transition-colors duration-150 hover:bg-rail"
            >
              openapi.json
              <Icon name="external" className="h-4 w-4" />
            </a>
          </div>
        </QuickCard>

        <QuickCard
          icon="check-shield"
          title="Authentication"
          body="Automation and interactive users authenticate separately. In development the API is open; elsewhere set AUTOMATION_API_KEYS and send X-API-Key."
        >
          <code className="block rounded-md bg-sunken px-3 py-2 font-mono text-[0.6875rem] leading-5 text-ink-2">
            X-API-Key: &lt;your service key&gt;
          </code>
        </QuickCard>
      </div>

      <Panel
        title="Generate a message from a pipeline"
        description="The same call the Create Message screen makes. Nothing here is UI-only."
        action={
          <SegmentedControl
            label="Language"
            value={language}
            onChange={setLanguage}
            options={(Object.keys(LANGUAGE_LABELS) as Language[]).map((id) => ({
              value: id,
              label: LANGUAGE_LABELS[id],
            }))}
          />
        }
        bodyClassName="px-0 py-0"
      >
        <CodeBlock code={samples[language]} label={LANGUAGE_LABELS[language]} />
      </Panel>

      <div className="grid gap-5 lg:grid-cols-2">
        <Panel
          title="Excel to message"
          description="Keep scenarios in a spreadsheet; get every message back in one response."
          bodyClassName="px-0 py-0"
        >
          <CodeBlock code={samples.excel} label="curl" />
        </Panel>
        <Panel
          title="What comes back"
          description="Validation is always actionable — never just valid=true."
          bodyClassName="px-0 py-0"
        >
          <CodeBlock code={RESPONSE_SAMPLE} label="Response" />
        </Panel>
      </div>

      <Panel
        title="Every endpoint"
        description={
          catalogue
            ? `${catalogue.messages.length} message types are generatable through these endpoints.`
            : "The complete automation surface."
        }
        bodyClassName="px-0 py-0"
      >
        <ul className="divide-y divide-line">
          {ENDPOINTS.map((endpoint) => (
            <li
              key={endpoint.path}
              className="flex flex-col gap-1 px-5 py-3 sm:flex-row sm:items-baseline sm:gap-4"
            >
              <Badge
                tone={endpoint.method === "POST" ? "accent" : "neutral"}
                className="w-14 shrink-0 justify-center font-mono"
              >
                {endpoint.method}
              </Badge>
              <code className="min-w-0 flex-1 break-all font-mono text-[0.8125rem] text-ink">
                {endpoint.path}
              </code>
              <span className="text-[0.8125rem] leading-6 text-ink-2 sm:w-[22rem] sm:shrink-0">
                {endpoint.body}
              </span>
            </li>
          ))}
        </ul>
      </Panel>
    </div>
  );
}

function QuickCard({
  icon,
  title,
  body,
  children,
}: {
  icon: "sheet" | "terminal" | "check-shield";
  title: string;
  body: string;
  children: React.ReactNode;
}) {
  return (
    <div className="flex min-w-0 flex-col gap-3 rounded-lg border border-line bg-panel p-5 shadow-[var(--shadow-1)]">
      <div className="flex items-center gap-2">
        <span className="flex h-8 w-8 items-center justify-center rounded-md bg-accent-sk text-accent">
          <Icon name={icon} className="h-4 w-4" />
        </span>
        <h2 className="text-[0.9375rem] font-semibold tracking-[-0.01em]">{title}</h2>
      </div>
      <p className="text-sm leading-6 text-ink-2">{body}</p>
      <div className="mt-auto pt-1">{children}</div>
    </div>
  );
}

function CodeBlock({ code, label }: { code: string; label?: string }) {
  return (
    <div className="proof min-w-0 bg-proof">
      {/* A header bar rather than a floating button: a long code line scrolls under an
          absolutely positioned control and hides it. */}
      <div className="flex items-center justify-between gap-3 border-b border-proof-line px-4 py-2">
        <span className="truncate font-mono text-[0.6875rem] uppercase tracking-[0.06em] text-proof-dim">
          {label ?? "Example"}
        </span>
        <CopyButton value={code} onProof />
      </div>
      <pre className="scroll-slim on-proof overflow-x-auto px-5 py-4 font-mono text-[0.8125rem] leading-[1.65] text-proof-ink">
        {code}
      </pre>
    </div>
  );
}

function buildSamples(base: string): Record<Language | "excel", string> {
  return {
    curl: `curl -X POST ${base}/api/v1/messages/generate \\
  -H 'Content-Type: application/json' \\
  -d '{
    "format": "MT",
    "messageType": "MT541",
    "profileId": "BASE_DEMO_V1",
    "scenarioId": "TC001",
    "fields": [
      { "sequence": "GENL",    "tag": "20C", "qualifier": "SEME", "value": "TESTREF001" },
      { "sequence": "GENL",    "tag": "23G",                      "value": "NEWM" },
      { "sequence": "TRADDET", "tag": "98A", "qualifier": "TRAD", "value": "20260814" },
      { "sequence": "TRADDET", "tag": "98A", "qualifier": "SETT", "value": "20260818" },
      { "sequence": "TRADDET", "tag": "35B",                      "value": "ISIN XS0000000001" },
      { "sequence": "TRADDET", "tag": "36B", "qualifier": "SETT", "value": "UNIT/1000" },
      { "sequence": "TRADDET", "tag": "22F", "qualifier": "SETR", "value": "BUY" },
      { "sequence": "FIAC",    "tag": "97A", "qualifier": "SAFE", "value": "SAFE0000001" },
      { "sequence": "SETDET",  "tag": "22F", "qualifier": "SETR", "value": "RECE" },
      { "sequence": "SETDET",  "tag": "95R", "qualifier": "PSET", "value": "CSD/DEMOPSET01" },
      { "sequence": "SETDET",  "tag": "95R", "qualifier": "DEAG", "value": "AGT/DEMODEAG01" },
      { "sequence": "SETDET",  "tag": "95R", "qualifier": "REAG", "value": "AGT/DEMOREAG01" },
      { "sequence": "SETDET",  "tag": "19A", "qualifier": "SETT", "value": "USD25000,00" }
    ]
  }' | jq -r '.outputs.fin'`,

    java: `// Java + REST Assured
import io.restassured.RestAssured;
import io.restassured.response.Response;
import static io.restassured.RestAssured.given;

public class GenerateMt541 {

    @Test
    void generatesAFinMessage() {
        RestAssured.baseURI = "${base}";

        String body = """
            {
              "format": "MT",
              "messageType": "MT541",
              "profileId": "BASE_DEMO_V1",
              "scenarioId": "TC001",
              "fields": [
                { "sequence": "GENL",    "tag": "20C", "qualifier": "SEME", "value": "TESTREF001" },
                { "sequence": "GENL",    "tag": "23G",                      "value": "NEWM" },
                { "sequence": "TRADDET", "tag": "98A", "qualifier": "SETT", "value": "20260818" }
              ]
            }
            """;

        Response response = given()
                .contentType("application/json")
                // .header("X-API-Key", System.getenv("STUDIO_API_KEY"))  // outside development
                .body(body)
            .when()
                .post("/api/v1/messages/generate")
            .then()
                .statusCode(200)
                .body("valid", equalTo(true))
                .extract().response();

        String fin = response.path("outputs.fin");
        // Hand \`fin\` straight to the system under test — the bytes are exactly as generated.
    }
}`,

    python: `import requests

BASE = "${base}"

payload = {
    "format": "MX",
    "messageType": "sese.023",
    "profileId": "BASE_DEMO_V1",
    "scenarioId": "MX001",
    "elements": [
        {"path": "/Document/SctiesSttlmTxInstr/TxId", "value": "TEST001"},
        {"path": "/Document/SctiesSttlmTxInstr/SttlmTpAndAddtlParams/SctiesMvmntTp", "value": "RECE"},
        {"path": "/Document/SctiesSttlmTxInstr/SttlmTpAndAddtlParams/Pmt", "value": "APMT"},
        {"path": "/Document/SctiesSttlmTxInstr/TradDtls/SttlmDt/Dt/Dt", "value": "2026-08-18"},
        {"path": "/Document/SctiesSttlmTxInstr/FinInstrmId/ISIN", "value": "XS0000000001"},
        {"path": "/Document/SctiesSttlmTxInstr/QtyAndAcctDtls/SttlmQty/Qty/Unit", "value": "1000"},
        {"path": "/Document/SctiesSttlmTxInstr/QtyAndAcctDtls/SfkpgAcct/Id", "value": "SAFE0000001"},
        {"path": "/Document/SctiesSttlmTxInstr/SttlmParams/SctiesTxTp/Cd", "value": "TRAD"},
        {"path": "/Document/SctiesSttlmTxInstr/DlvrgSttlmPties/Pty1/Id/AnyBIC", "value": "DEMODEAGXXX"},
        {"path": "/Document/SctiesSttlmTxInstr/SttlmAmt/Amt", "value": "USD 25000.00"},
        {"path": "/Document/SctiesSttlmTxInstr/SttlmAmt/CdtDbtInd", "value": "DBIT"},
    ],
}

result = requests.post(f"{BASE}/api/v1/messages/generate", json=payload, timeout=30).json()

assert result["valid"], [issue["message"] for issue in result["validation"]["errors"]]
xml = result["outputs"]["xml"]          # AppHdr + Document, ready to send
document = result["outputs"]["document"]  # the Document on its own`,

    javascript: `// Playwright, Jest or any Node runner
const BASE = "${base}";

const response = await fetch(\`\${BASE}/api/v1/messages/generate\`, {
  method: "POST",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({
    format: "MT",
    messageType: "MT541",
    scenarioId: "TC001",
    fields: [
      { sequence: "GENL", tag: "20C", qualifier: "SEME", value: "TESTREF001" },
      { sequence: "GENL", tag: "23G", value: "NEWM" },
    ],
  }),
});

const result = await response.json();
if (!result.valid) {
  throw new Error(
    result.validation.errors.map((e) => \`\${e.field}: \${e.message}\`).join("\\n"),
  );
}
console.log(result.outputs.fin);`,

    excel: `# Keep your scenarios in a spreadsheet, get every message back at once.
curl -X POST '${base}/api/v1/messages/generate-from-excel?profileId=BASE_DEMO_V1' \\
  -F 'file=@scenarios.xlsx' | jq '.results[] | {
      scenarioId,
      messageType,
      valid,
      summary: .validation.summary,
      message: (.outputs.fin // .outputs.xml)
    }'

# Download the template first so the columns are right:
curl -o mt-template.xlsx '${base}/api/v1/templates/MT.xlsx'
curl -o mx-template.xlsx '${base}/api/v1/templates/MX.xlsx'`,
  };
}

const RESPONSE_SAMPLE = `{
  "messageId": "8f2c…",
  "correlationId": "b41e…",
  "scenarioId": "TC001",
  "format": "MT",
  "messageType": "MT541",
  "profileId": "BASE_DEMO_V1",
  "valid": false,
  "validation": {
    "summary": "1 issue needs attention",
    "errors": [
      {
        "ruleId": "MT_MANDATORY_FIELD_MISSING",
        "severity": "ERROR",
        "layer": "STRUCTURE",
        "field": "Settlement Amount",
        "location": "MT541-E-19A-SETT",
        "message": "Settlement Amount is required.",
        "expected": "ISO currency plus a positive decimal amount",
        "suggestion": "For example: USD25000,00"
      }
    ],
    "warnings": [],
    "layers": [
      { "layer": "STRUCTURE", "state": "FAILED", "detail": "1 issue(s) found." },
      { "layer": "FORMAT", "state": "PASSED", "detail": "No issues found." }
    ]
  },
  "outputs": {
    "block4": "{4:\\n:16R:GENL\\n…\\n-}",
    "fin": "{1:F01DEMOGB2LAXXX0001000001}\\n{2:I541DEMOUS33XXXXN}\\n{4:\\n…\\n-}",
    "canonicalJson": { "…": "…" }
  },
  "checksum": "2c57614539b5…",
  "availableOutputModes": ["BLOCK4", "FIN", "TXT", "CANONICAL_JSON"]
}`;
