"""Read an ISO 20022 XML document back into canonical element values.

This is the exact inverse of :mod:`app.studio.mx.generator`'s composer, and it is
deliberately the *only* thing it does. Import produces ``ElementInput`` values — the same
type the JSON API and the Excel importer produce — and then hands them to the ordinary
generation path. There is no second composer, no second validator and no import-only
rendering: a message that has been imported is regenerated by the code that generates every
other message, so the two can never disagree.

The round-trip property the tests hold this to is::

    Compose(Parse(Compose(values))) == Compose(values)

Occurrence numbering is the subtle half. The composer threads a single occurrence index
through each repeatable container down into its non-repeatable descendants, so the parser
has to assign the same index while walking down or the values land in the wrong repeat.

Nothing is silently discarded. An element that is not in the configured subset, a repeat the
subset does not allow, a container holding text, an empty element and a structure the flat
occurrence model cannot represent are each reported as a named issue rather than dropped —
an import that quietly loses half a document is worse than one that refuses.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from xml.etree import ElementTree

from app.studio.models import (
    ElementInput,
    EnvelopeOverride,
    IssueSeverity,
    ValidationIssue,
    ValidationLayer,
)
from app.studio.mx.generator import APPHDR_DEFINITION, APPHDR_NAMESPACE
from app.studio.mx.models import MxElement, MxMessageSpec
from app.studio.mx.registry import MxRegistry, mx_registry

#: The synthetic root used when the pasted text holds two sibling roots — an AppHdr and a
#: Document downloaded separately and concatenated, which is not well-formed XML on its own.
_IMPORT_ROOT = "StudioImportRoot"

_DECLARATION = re.compile(r"^\s*<\?xml[^>]*\?>\s*", re.IGNORECASE)
_TAG = re.compile(r"^(?:\{(?P<ns>[^}]*)\})?(?P<name>.+)$")

#: Maximum accepted input size. Parsing is linear, but an unbounded paste is still a way to
#: spend the server's memory, and no realistic settlement message comes close to this.
MAX_IMPORT_BYTES = 1_000_000


class MxImportError(Exception):
    """The document could not be identified at all, so there is nothing to regenerate."""

    def __init__(self, issue: ValidationIssue) -> None:
        super().__init__(issue.message)
        self.issue = issue


@dataclass
class MxImportResult:
    specification: MxMessageSpec
    elements: list[ElementInput]
    envelope: EnvelopeOverride
    app_hdr_present: bool
    errors: list[ValidationIssue] = field(default_factory=list)
    warnings: list[ValidationIssue] = field(default_factory=list)


def _issue(
    rule_id: str,
    message: str,
    *,
    layer: ValidationLayer = ValidationLayer.CANONICAL,
    severity: IssueSeverity = IssueSeverity.ERROR,
    field_name: str | None = None,
    location: str | None = None,
    expected: str | None = None,
    current: str | None = None,
    suggestion: str | None = None,
) -> ValidationIssue:
    return ValidationIssue(
        rule_id=rule_id,
        severity=severity,
        layer=layer,
        field=field_name,
        location=location,
        message=message,
        expected=expected,
        current_value=current,
        suggestion=suggestion,
    )


def _split_tag(tag: str) -> tuple[str, str]:
    match = _TAG.match(tag)
    if match is None:  # pragma: no cover - ElementTree never produces an empty tag
        return "", tag
    return match.group("ns") or "", match.group("name")


# --------------------------------------------------------------------------------------
# Locating the parts
# --------------------------------------------------------------------------------------


def _load(xml: str) -> ElementTree.Element:
    """Parse the pasted text, tolerating the three shapes a tester can arrive with.

    A wrapped payload, a bare Document, or an AppHdr and a Document downloaded separately
    and pasted one after the other. Only the last needs help: two sibling roots is not a
    well-formed document, so it is wrapped before parsing rather than rejected.
    """
    text = xml.strip()
    if not text:
        raise MxImportError(
            _issue(
                "MX_IMPORT_EMPTY",
                "There is no XML to import.",
                layer=ValidationLayer.XML_WELL_FORMED,
                suggestion="Paste the generated message, or choose a file to upload.",
            )
        )
    if len(text.encode()) > MAX_IMPORT_BYTES:
        raise MxImportError(
            _issue(
                "MX_IMPORT_TOO_LARGE",
                "That document is larger than the studio accepts for import.",
                layer=ValidationLayer.XML_WELL_FORMED,
                expected=f"Up to {MAX_IMPORT_BYTES:,} bytes",
                suggestion="Import one message at a time.",
            )
        )
    try:
        return ElementTree.fromstring(text)
    except ElementTree.ParseError as first_error:
        body = _DECLARATION.sub("", text)
        # Only retry when the input actually looks like markup. Wrapping unconditionally
        # would make plain prose parse as a valid empty root, and the tester would be told
        # their text contained no Document rather than that it was not XML.
        try:
            if not body.lstrip().startswith("<"):
                raise ElementTree.ParseError("not markup")
            return ElementTree.fromstring(f"<{_IMPORT_ROOT}>{body}</{_IMPORT_ROOT}>")
        except ElementTree.ParseError:
            raise MxImportError(
                _issue(
                    "MX_IMPORT_NOT_WELL_FORMED",
                    f"That is not well-formed XML: {first_error}.",
                    layer=ValidationLayer.XML_WELL_FORMED,
                    suggestion="Check for a missing closing tag, and paste the whole message "
                    "including its opening element.",
                )
            ) from first_error


def _find(root: ElementTree.Element, predicate) -> ElementTree.Element | None:  # type: ignore[no-untyped-def]
    """Depth-first search including the root, so any transport wrapper is transparent."""
    if predicate(root):
        return root
    for node in root.iter():
        if predicate(node):
            return node
    return None


def _document_of(
    root: ElementTree.Element, registry: MxRegistry | None = None
) -> tuple[ElementTree.Element, MxMessageSpec]:
    """Identify the message from the document namespace, never from the element name."""
    lookup = registry or mx_registry
    found: list[tuple[ElementTree.Element, MxMessageSpec]] = []
    seen_namespaces: set[str] = set()
    for node in [root, *root.iter()]:
        namespace, _ = _split_tag(node.tag)
        if not namespace.startswith("urn:iso:std:iso:20022:tech:xsd:"):
            continue
        if namespace == APPHDR_NAMESPACE:
            continue
        seen_namespaces.add(namespace)
        spec = lookup.by_namespace(namespace)
        if spec is not None and not any(node is existing for existing, _ in found):
            found.append((node, spec))
            break
    if found:
        return found[0]
    if seen_namespaces:
        raise MxImportError(
            _issue(
                "MX_IMPORT_MESSAGE_NOT_CONFIGURED",
                f"{sorted(seen_namespaces)[0]} is a valid ISO 20022 namespace, but that "
                "message is not configured in this repository.",
                layer=ValidationLayer.STRUCTURE,
                current=sorted(seen_namespaces)[0],
                expected=", ".join(lookup.namespaces()),
                suggestion="Import one of the configured messages, or add the message "
                "specification to backend/config/mx.",
            )
        )
    raise MxImportError(
        _issue(
            "MX_IMPORT_NO_DOCUMENT",
            "No ISO 20022 Document was found in that XML.",
            layer=ValidationLayer.STRUCTURE,
            expected=", ".join(lookup.namespaces()),
            suggestion="Paste the Document element, including its xmlns declaration — the "
            "namespace is what identifies the message.",
        )
    )


# --------------------------------------------------------------------------------------
# Document body
# --------------------------------------------------------------------------------------


class _DocumentReader:
    def __init__(self, spec: MxMessageSpec) -> None:
        self._spec = spec
        self._elements: list[ElementInput] = []
        self._errors: list[ValidationIssue] = []
        self._warnings: list[ValidationIssue] = []
        self._claimed: dict[tuple[str, int], str] = {}

    def read(self, document: ElementTree.Element) -> None:
        root_path = f"/{self._spec.document_element}/{self._spec.message_root}"
        children = list(document)
        message_root = None
        for node in children:
            _, name = _split_tag(node.tag)
            if name == self._spec.message_root:
                message_root = node
                break
        if message_root is None:
            self._errors.append(
                _issue(
                    "MX_IMPORT_ROOT_MISMATCH",
                    f"The document does not contain the expected {self._spec.message_root} "
                    "element.",
                    layer=ValidationLayer.STRUCTURE,
                    expected=self._spec.message_root,
                    current=", ".join(_split_tag(node.tag)[1] for node in children) or "nothing",
                    suggestion=f"A {self._spec.message_type} document holds a single "
                    f"{self._spec.message_root} element.",
                )
            )
            return
        self._walk(message_root, self._spec.structure, root_path, occurrence=1)

    @property
    def result(self) -> tuple[list[ElementInput], list[ValidationIssue], list[ValidationIssue]]:
        return self._elements, self._errors, self._warnings

    def _walk(
        self,
        node: ElementTree.Element,
        specification: list[MxElement],
        path: str,
        *,
        occurrence: int,
    ) -> None:
        by_name = {child.name: child for child in specification}
        order = {child.name: index for index, child in enumerate(specification)}
        counts: dict[str, int] = {}
        highest_order = -1
        reported_order = False

        for child_node in node:
            namespace, name = _split_tag(child_node.tag)
            child_path = f"{path}/{name}"
            if namespace and namespace != self._spec.namespace:
                self._errors.append(
                    _issue(
                        "MX_IMPORT_FOREIGN_NAMESPACE",
                        f"'{name}' is in namespace {namespace}, which is not the namespace of "
                        f"{self._spec.message_type}.",
                        layer=ValidationLayer.STRUCTURE,
                        location=child_path,
                        expected=self._spec.namespace,
                        current=namespace,
                        suggestion="Elements of the document must all be in the message "
                        "namespace.",
                    )
                )
                continue
            element = by_name.get(name)
            if element is None:
                self._errors.append(
                    _issue(
                        "MX_IMPORT_UNKNOWN_ELEMENT",
                        f"'{name}' is not part of the configured {self._spec.message_type} "
                        "subset, so its value cannot be imported.",
                        layer=ValidationLayer.STRUCTURE,
                        location=child_path,
                        current=name,
                        expected=", ".join(child.name for child in specification),
                        suggestion="Remove the element, or add it to the message "
                        "specification in backend/config/mx.",
                    )
                )
                continue

            position = order[name]
            if position < highest_order and not reported_order:
                reported_order = True
                self._warnings.append(
                    _issue(
                        "MX_IMPORT_ELEMENT_ORDER",
                        f"The children of {path.rsplit('/', 1)[-1]} are not in specification "
                        "order in the imported document.",
                        layer=ValidationLayer.STRUCTURE,
                        severity=IssueSeverity.WARNING,
                        location=child_path,
                        suggestion="The values were still read. Regenerating writes them back "
                        "in the correct order.",
                    )
                )
            highest_order = max(highest_order, position)

            index = counts.get(name, 0) + 1
            counts[name] = index
            if element.max_occurs > 1:
                child_occurrence = index
            else:
                if index > 1:
                    self._errors.append(
                        _issue(
                            "MX_IMPORT_UNEXPECTED_REPEAT",
                            f"{element.display_name} appears {index} times, but the configured "
                            "subset allows it once.",
                            layer=ValidationLayer.STRUCTURE,
                            field_name=element.display_name,
                            location=child_path,
                            expected="1 occurrence",
                            suggestion="Remove the duplicate, or raise maxOccurs in the "
                            "message specification.",
                        )
                    )
                    continue
                child_occurrence = occurrence

            if element.is_leaf:
                self._read_leaf(child_node, element, child_path, child_occurrence)
            else:
                self._read_container(child_node, element, child_path, child_occurrence)

    def _read_container(
        self,
        node: ElementTree.Element,
        element: MxElement,
        path: str,
        occurrence: int,
    ) -> None:
        text = (node.text or "").strip()
        if text:
            self._errors.append(
                _issue(
                    "MX_IMPORT_TEXT_IN_CONTAINER",
                    f"{element.display_name} is a container but holds the text '{text}'.",
                    layer=ValidationLayer.STRUCTURE,
                    field_name=element.display_name,
                    location=path,
                    current=text,
                    suggestion="Move the value onto one of the child elements.",
                )
            )
        self._walk(node, element.children, path, occurrence=occurrence)

    def _read_leaf(
        self,
        node: ElementTree.Element,
        element: MxElement,
        path: str,
        occurrence: int,
    ) -> None:
        if len(node):
            self._errors.append(
                _issue(
                    "MX_IMPORT_UNEXPECTED_CHILDREN",
                    f"{element.display_name} holds a value in the configured subset, but the "
                    "imported document nests further elements inside it.",
                    layer=ValidationLayer.STRUCTURE,
                    field_name=element.display_name,
                    location=path,
                    current=", ".join(_split_tag(child.tag)[1] for child in node),
                    suggestion="Import a document that matches the configured subset, or "
                    "extend the specification.",
                )
            )
            return

        text = (node.text or "").strip()
        currency = node.get("Ccy")
        if element.currency_attribute and currency:
            # The composer splits "EUR 25000.00" into a Ccy attribute and the bare amount;
            # rejoining them restores the single canonical value a tester typed.
            value = f"{currency} {text}".strip()
        else:
            value = text
            if currency:
                self._warnings.append(
                    _issue(
                        "MX_IMPORT_UNEXPECTED_CURRENCY",
                        f"{element.display_name} carries a Ccy attribute, which the configured "
                        "subset does not define for it. The attribute was not imported.",
                        layer=ValidationLayer.STRUCTURE,
                        severity=IssueSeverity.WARNING,
                        field_name=element.display_name,
                        location=path,
                        current=currency,
                    )
                )

        if not value:
            self._errors.append(
                _issue(
                    "MX_IMPORT_EMPTY_ELEMENT",
                    f"{element.display_name} is present in the document but empty.",
                    layer=ValidationLayer.STRUCTURE,
                    field_name=element.display_name,
                    location=path,
                    suggestion="Give the element a value, or remove it from the document.",
                )
            )
            return

        key = (path, occurrence)
        previous = self._claimed.get(key)
        if previous is not None:
            # Two different repeats resolved to the same (path, occurrence) address. That
            # happens when a repeatable block is nested inside another repeatable block:
            # the flat occurrence index the composer uses cannot tell the two apart, so
            # importing would quietly overwrite one with the other.
            self._errors.append(
                _issue(
                    "MX_IMPORT_NESTED_REPEAT_UNSUPPORTED",
                    f"{element.display_name} occurs inside nested repeating blocks, which this "
                    "platform's element addressing cannot represent.",
                    layer=ValidationLayer.CANONICAL,
                    field_name=element.display_name,
                    location=f"{path}[{occurrence}]",
                    current=value,
                    expected=previous,
                    suggestion="Import a document without repeats nested inside repeats.",
                )
            )
            return
        self._claimed[key] = value
        self._elements.append(ElementInput(path=path, occurrence=occurrence, value=value))


# --------------------------------------------------------------------------------------
# Business Application Header
# --------------------------------------------------------------------------------------


def _text_at(node: ElementTree.Element, *names: str) -> str | None:
    """Follow a chain of child names, ignoring namespaces."""
    current: ElementTree.Element | None = node
    for name in names:
        if current is None:
            return None
        current = next(
            (child for child in current if _split_tag(child.tag)[1] == name),
            None,
        )
    if current is None:
        return None
    text = (current.text or "").strip()
    return text or None


def _read_app_hdr(
    spec: MxMessageSpec, header: ElementTree.Element
) -> tuple[EnvelopeOverride, list[ValidationIssue], list[ValidationIssue]]:
    errors: list[ValidationIssue] = []
    warnings: list[ValidationIssue] = []

    definition = _text_at(header, "MsgDefIdr")
    if definition and definition != spec.version:
        errors.append(
            _issue(
                "MX_IMPORT_APPHDR_MISMATCH",
                "The header says this is a different message from the one the document "
                "actually contains.",
                layer=ValidationLayer.APPHDR_CONSISTENCY,
                field_name="Message Definition Identifier (MsgDefIdr)",
                location="/AppHdr/MsgDefIdr",
                expected=spec.version,
                current=definition,
                suggestion="Correct MsgDefIdr, or import the document the header describes.",
            )
        )

    override = EnvelopeOverride(
        sender=_text_at(header, "Fr", "FIId", "FinInstnId", "BICFI"),
        receiver=_text_at(header, "To", "FIId", "FinInstnId", "BICFI"),
        business_message_identifier=_text_at(header, "BizMsgIdr"),
        creation_date=_text_at(header, "CreDt"),
    )
    if _text_at(header, "Sgntr") is not None:
        warnings.append(
            _issue(
                "MX_IMPORT_SIGNATURE_DROPPED",
                "The imported header carries a signature. Signatures are applied by the "
                "messaging infrastructure, so it was read but will not be reproduced.",
                layer=ValidationLayer.APPHDR_CONSISTENCY,
                severity=IssueSeverity.WARNING,
                field_name="Signature (Sgntr)",
                location="/AppHdr/Sgntr",
                suggestion="Regenerating produces an unsigned header, as it always does.",
            )
        )
    return override, errors, warnings


# --------------------------------------------------------------------------------------
# Entry point
# --------------------------------------------------------------------------------------


def parse_message(xml: str, registry: MxRegistry | None = None) -> MxImportResult:
    """Read an ISO 20022 document into canonical element values.

    :raises MxImportError: when the message cannot be identified, which is the only failure
        that leaves nothing to hand to the generator.
    """
    root = _load(xml)
    document, spec = _document_of(root, registry)

    reader = _DocumentReader(spec)
    reader.read(document)
    elements, errors, warnings = reader.result

    header = _find(
        root,
        lambda node: _split_tag(node.tag) == (APPHDR_NAMESPACE, "AppHdr")
        or _split_tag(node.tag)[1] == "AppHdr",
    )
    envelope = EnvelopeOverride()
    if header is not None:
        namespace, _ = _split_tag(header.tag)
        if namespace and namespace != APPHDR_NAMESPACE:
            warnings.append(
                _issue(
                    "MX_IMPORT_APPHDR_VERSION",
                    f"The header uses {namespace}. This platform writes "
                    f"{APPHDR_DEFINITION}, so the regenerated header will use that.",
                    layer=ValidationLayer.APPHDR_CONSISTENCY,
                    severity=IssueSeverity.WARNING,
                    location="/AppHdr",
                    expected=APPHDR_NAMESPACE,
                    current=namespace,
                )
            )
        envelope, header_errors, header_warnings = _read_app_hdr(spec, header)
        errors.extend(header_errors)
        warnings.extend(header_warnings)

    if not elements and not errors:
        errors.append(
            _issue(
                "MX_IMPORT_NO_VALUES",
                "The document was recognised but contains no element values to import.",
                layer=ValidationLayer.CANONICAL,
                suggestion="Check that you pasted the whole message, not just its opening "
                "elements.",
            )
        )

    return MxImportResult(
        specification=spec,
        elements=elements,
        envelope=envelope,
        app_hdr_present=header is not None,
        errors=errors,
        warnings=warnings,
    )
