"""The three generated knowledge documents.

Rendered from the local knowledge database and the preview registries — ids, hashes,
counts, pages and readiness, never source text. Deterministic: no timestamps, so two
renders of the same state are byte-identical. They are regenerated by the operator after a
sync (``make knowledge-reports-write``) and committed as derived metadata.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from pathlib import Path

from app.config import PROJECT_ROOT, get_settings

DOCS = PROJECT_ROOT / "docs" / "generated"
READINESS_DOC = DOCS / "universal-message-readiness.md"
COVERAGE_DOC = DOCS / "knowledge-rag-coverage.md"
SAMPLE_DOC = DOCS / "ai-sample-readiness.md"
GENERATION_DOC = DOCS / "universal-mt-generation-coverage.md"
BLOCKERS_DOC = DOCS / "mt-generation-blockers.md"

NOT_AVAILABLE = (
    "SOURCE_NOT_AVAILABLE: no knowledge database is present on this machine. Run "
    "`make knowledge-sync` with the operator's sources, then `make knowledge-reports-write`."
)


def _normalise(lines: list[str]) -> str:
    """One trailing newline, never a blank last line — `git diff --check` refuses one."""
    text = "\n".join(lines).rstrip("\n")
    return text + "\n"


def render_readiness() -> str:
    from app.knowledge_base.preview import preview_registries
    from app.knowledge_base.service import knowledge_service

    lines = [
        "# Universal message readiness",
        "",
        "Generated by `python -m app.knowledge_base reports`. The honest answer to *what can I "
        "test?*: one row per message and release the knowledge base knows, with what its "
        "structure rests on and exactly what blocks generation where it is blocked. "
        "Configured messages are listed first; they are unchanged by Phase 6.",
        "",
    ]
    if not knowledge_service.indexed:
        lines.append(NOT_AVAILABLE)
        return _normalise(lines)
    registries = preview_registries()
    sources = knowledge_service.source_counts()
    by_key: dict[tuple[str, str, str], dict[str, object]] = {}
    for (fmt, mt, release), status in registries.structures.items():
        by_key[(fmt, mt, release)] = {
            "structureSource": status.structure_source,
            "readiness": status.readiness.value,
            "blockers": ", ".join(status.blockers) or "—",
            "gates": "/".join(name for name, result in status.gates.items() if result.get("passed"))
            or "—",
            "sources": sources.get((fmt, mt, release), 0),
        }
    for key, count in sources.items():
        by_key.setdefault(
            key,
            {
                "structureSource": "—",
                "readiness": "KNOWLEDGE_ONLY",
                "blockers": "STRUCTURE_SOURCE_MISSING",
                "gates": "—",
                "sources": count,
            },
        )
    totals = Counter(str(item["readiness"]) for item in by_key.values())
    lines += [
        "## Summary",
        "",
        f"- Messages/releases discovered: {len(by_key)}",
        f"- Generation ready (knowledge-preview lane): {totals.get('GENERATION_READY', 0)}",
        f"- Structure verified, round trip not established: {totals.get('STRUCTURE_VERIFIED', 0)}",
        f"- Structure evidence available, generation not established: "
        f"{totals.get('STRUCTURE_AVAILABLE', 0)}",
        f"- Knowledge only: {totals.get('KNOWLEDGE_ONLY', 0)}",
        "",
        "`GENERATION_READY` means the pack loaded, a deterministic sample validated, composed, "
        "parsed back and re-composed identically (MX: and the source XSD accepted it). It does "
        "not mean complete semantic rules, SWIFT certification or conformance.",
        "",
        "## Configured lane (unchanged)",
        "",
    ]
    from app.specifications.registry import specification_registry
    from app.studio.mx.registry import mx_registry

    lines += [
        "| Format | Message | Release/version | Structure source | Rules | Status |",
        "|---|---|---|---|---|---|",
    ]
    for spec in specification_registry.list():
        lines.append(
            f"| MT | {spec.message_type} | {spec.standards_release} | configured YAML | "
            f"configured + reviewed packs | Configured & validated |"
        )
    for mx_spec in mx_registry.all_specs():
        lines.append(
            f"| MX | {mx_spec.message_type} | {mx_spec.version} | configured YAML | "
            f"configured + reviewed packs | Configured & validated |"
        )
    lines += [
        "",
        "## Knowledge-preview lane",
        "",
        "| Format | Message | Release/version | Source docs | Structure source | Readiness | "
        "Gates passed | Blocking reason |",
        "|---|---|---|---|---|---|---|---|",
    ]
    from app.studio.catalogue import _shadowed_by_configured
    from app.studio.models import MessageFormat

    shadowed = 0
    for (fmt, mt, release), item in sorted(by_key.items()):
        readiness = item["readiness"]
        if _shadowed_by_configured(MessageFormat(fmt), mt, release or ""):
            shadowed += 1
            readiness = f"{readiness} (not listed: configured lane serves this release)"
        lines.append(
            f"| {fmt} | {mt} | {release or '—'} | {item['sources']} | {item['structureSource']} | "
            f"{readiness} | {item['gates']} | {item['blockers']} |"
        )
    lines += [
        "",
        "Rules status for every preview row: NOT_ESTABLISHED (candidate packs, where a guide "
        "exists, remain REVIEW_REQUIRED). RAG indexed: every row with a source document. "
        "Embedding indexed: see knowledge-rag-coverage.md. Excel and JSON API: available for "
        "every GENERATION_READY row through `lane=KNOWLEDGE_PREVIEW`.",
    ]
    if shadowed:
        lines += [
            "",
            f"{shadowed} preview structure(s) above carry the same message and current-live "
            "release as a configured pack. The catalogue does not list them beside the "
            "configured entry — the reviewed pack is the authority for that release — but "
            "their structure evidence is recorded here and on "
            "`GET /api/v1/knowledge/messages/{message}/status`.",
        ]
    return _normalise(lines)


def render_coverage() -> str:
    from app.knowledge_base.service import knowledge_service

    lines = [
        "# Knowledge RAG coverage",
        "",
        "Generated by `python -m app.knowledge_base reports`. Sources, segments and embedding "
        "state of the local knowledge base. Checksums identify documents; no text is quoted.",
        "",
    ]
    if not knowledge_service.indexed:
        lines.append(NOT_AVAILABLE)
        return _normalise(lines)
    sources = knowledge_service.sources()
    live = [s for s in sources if not s.deleted]
    counts = knowledge_service.database.counts()
    last_run = knowledge_service.database.last_run() or {}
    stats = last_run.get("stats", {}) if isinstance(last_run, dict) else {}
    by_state = Counter(s.ingestion_state.value for s in live)
    blocked = sum(1 for s in live if s.embedding_policy.value == "BLOCKED")
    releases = sorted({s.release for s in live if s.release})
    messages = sorted({s.message_version or s.message_type or "" for s in live if s.message_type})
    checksums = Counter(s.checksum for s in sources)
    duplicates = sum(1 for _c, n in checksums.items() if n > 1)
    paths_per_source = sum(len(s.relative_paths) for s in live) - len(live)
    lines += [
        "## Totals",
        "",
        f"- Sources discovered: {len(sources)} (deleted/tombstoned: {len(sources) - len(live)})",
        f"- Sources indexed: {len(live)}",
        f"- Pages: {sum(s.page_count or 0 for s in live)}",
        f"- Segments: {counts.get('segments', 0)}",
        f"- Messages: {len(messages)}",
        f"- Releases: {', '.join(releases) or '—'}",
        f"- FTS indexed segments: {counts.get('segments', 0)}",
        f"- Embedding indexed segments: {counts.get('embeddings', 0)}",
        f"- Sources embedding-blocked by policy: {blocked} of {len(live)}",
        f"- Failed: {by_state.get('FAILED', 0)} · Unsupported: {by_state.get('UNSUPPORTED', 0)}",
        f"- Duplicate sources (same bytes, several paths): {duplicates + max(0, paths_per_source)}",
        f"- Last run — chunks reused: {stats.get('segmentsReused', 0)}, embedding cache hits: "
        f"{stats.get('embeddingCacheHits', 0)}, embedding requests: "
        f"{stats.get('embeddingRequests', 0)}, requests avoided: "
        f"{stats.get('embeddingRequestsAvoided', 0)}",
        "",
        "## Sources",
        "",
        "| Source id | Format | Message | Release/version | Type | Pages | Segments | "
        "Embedded | Embedding policy | State | Checksum |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for s in sorted(live, key=lambda item: item.source_id):
        lines.append(
            f"| {s.source_id} | {s.format.value} | {s.message_type or '—'} | "
            f"{s.message_version or s.release or '—'} | {s.document_type.value} | "
            f"{s.page_count or '—'} | {s.segment_count} | {s.embedded_count} | "
            f"{s.embedding_policy.value} | {s.ingestion_state.value} | "
            f"sha256:{s.checksum[:16]}… |"
        )
    return _normalise(lines)


def render_sample_readiness() -> str:
    from app.knowledge_base.preview import preview_registries
    from app.knowledge_base.service import knowledge_service
    from app.studio.catalogue import message_spec
    from app.studio.models import Lane, MessageFormat, Presence

    settings = get_settings()
    lines = [
        "# AI sample readiness",
        "",
        "Generated by `python -m app.knowledge_base reports`. For every generation-ready "
        "message: which sample types are structurally meaningful and whether a validated AI "
        "sample is already cached. Samples are generated lazily on first request and cached; "
        "nothing here was generated in bulk.",
        "",
        "Statuses: CACHE_READY (validated sample cached, 0 model calls on next request), "
        "AI_READY (provider configured, first request will generate), DETERMINISTIC_FALLBACK "
        "(no provider; the deterministic sample serves), N/A (variant not offered).",
        "",
    ]
    if not knowledge_service.indexed:
        lines.append(NOT_AVAILABLE)
        return _normalise(lines)
    provider = settings.structured_ai_provider_effective
    registries = preview_registries()
    rows: list[tuple[str, str, str, str, str, str, str]] = []

    def status_for(fmt: str, mt: str, release: str, variant: str, offered: bool) -> str:
        if not offered:
            return "N/A"
        if knowledge_service.sample_cached(fmt, mt, release):
            return "CACHE_READY"
        return "AI_READY" if provider != "disabled" else "DETERMINISTIC_FALLBACK"

    from app.specifications.registry import specification_registry
    from app.studio.mx.registry import mx_registry

    def variants_of(spec_fields: list[object]) -> tuple[bool, bool, bool]:
        mandatory = sum(
            1 for f in spec_fields if getattr(f, "presence", None) is Presence.MANDATORY
        )
        total = len(spec_fields)
        return True, mandatory < total, mandatory < total <= 500

    for spec in specification_registry.list():
        projected = message_spec(MessageFormat.MT, spec.message_type)
        minimal, typical, full = variants_of(list(projected.fields))
        rows.append(
            (
                "MT",
                spec.message_type,
                "configured",
                "CONFIGURED",
                status_for("MT", spec.message_type, "", "MINIMAL", minimal),
                status_for("MT", spec.message_type, "", "TYPICAL", typical),
                status_for("MT", spec.message_type, "", "FULL", full),
            )
        )
    for mx_spec in mx_registry.all_specs():
        projected = message_spec(MessageFormat.MX, mx_spec.version)
        minimal, typical, full = variants_of(list(projected.fields))
        rows.append(
            (
                "MX",
                mx_spec.message_type,
                mx_spec.version,
                "CONFIGURED",
                status_for("MX", mx_spec.message_type, mx_spec.version, "MINIMAL", minimal),
                status_for("MX", mx_spec.message_type, mx_spec.version, "TYPICAL", typical),
                status_for("MX", mx_spec.message_type, mx_spec.version, "FULL", full),
            )
        )
    for (fmt, mt, release), status in sorted(registries.structures.items()):
        if not status.generation_ready:
            continue
        try:
            projected = message_spec(
                MessageFormat(fmt),
                mt if fmt == "MT" else release,
                Lane.KNOWLEDGE_PREVIEW,
                release if fmt == "MT" else None,
            )
        except (LookupError, KeyError):
            continue
        minimal, _typical, full = variants_of(list(projected.fields))
        rows.append(
            (
                fmt,
                mt,
                release,
                "KNOWLEDGE_PREVIEW",
                status_for(fmt, mt, release, "MINIMAL", minimal),
                "N/A",
                status_for(fmt, mt, release, "FULL", full),
            )
        )
    cached = sum(1 for r in rows if "CACHE_READY" in r[4:])
    lines += [
        f"- Generation-ready messages listed: {len(rows)}",
        f"- With a cached validated AI sample: {cached}",
        f"- AI provider configured: {'yes' if provider != 'disabled' else 'no'} "
        f"({provider if provider != 'disabled' else 'deterministic fallback only'})",
        "",
        "| Format | Message | Release/version | Lane | Minimal | Typical | Full |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return _normalise(lines)


# -- the universal MT generation matrix and its blockers ---------------------------------------

#: Root causes a blocked structure is filed under. Derived from the first failed gate and
#: the recorded blockers — the same classification the engagement plan uses, so the
#: document answers "what generic fix, or what missing evidence, stands behind this?".
ROOT_CAUSES: tuple[tuple[str, str, str], ...] = (
    (
        "PROWIDE_NO_BLOCK4_FIELDS",
        "The Prowide model states no Block 4 field groups and no guide exists; there is no "
        "structural evidence to compile.",
        "Missing evidence — not a generic defect.",
    ),
    (
        "QUALIFIER_EVIDENCE_MISSING",
        "Generic fields (``:4!c//``) whose legal qualifiers Prowide does not record; only a "
        "Message Reference Guide states them, and the SR2025 lane has none.",
        "Release-bound evidence gap — the same message is generation-ready in the SR2026 "
        "lane where its guide is read.",
    ),
    (
        "FORMAT_NOTATION_NOT_IN_SOURCE",
        "A mandatory field whose only notation is a Prowide-internal macro (``<?>``, "
        "``{65x}n``, ``<VAR-SEQU-n>``, ``<CC>[14<DATE1>]``) with no SWIFT spelling and no "
        "guide for the message.",
        "Missing evidence — a guess would be an invention.",
    ),
    ("STRUCTURE_COMPILATION_FAILED", "The pack compiler raised.", "Generic defect."),
    (
        "VALIDATION_FINDING",
        "The deterministic validator refused the synthetic sample.",
        "Generic defect.",
    ),
    ("PARSER_GAP", "The parser could not read the composed message back.", "Generic defect."),
    ("ROUND_TRIP_DIFFERENCE", "Compose(Parse(Compose(v))) differs.", "Generic defect."),
)

Gates = dict[str, dict[str, object]]


def _first_failed(gates: Gates) -> tuple[str, str] | None:
    for name, result in gates.items():
        if not result.get("passed"):
            return name, str(result.get("detail", ""))
    return None


def root_cause(readiness: str, blockers: tuple[str, ...], gates: Gates) -> str:
    if readiness == "GENERATION_READY":
        return "—"
    failed = _first_failed(gates)
    if failed is None or failed[0] == "LOAD":
        no_fields = "STRUCTURE_SOURCE_MISSING" in blockers or (
            failed is not None and "declares no sequences" in failed[1]
        )
        return "PROWIDE_NO_BLOCK4_FIELDS" if no_fields else "STRUCTURE_COMPILATION_FAILED"
    name, detail = failed
    if name == "SAMPLE":
        if "qualifier" in detail:
            return "QUALIFIER_EVIDENCE_MISSING"
        return "FORMAT_NOTATION_NOT_IN_SOURCE"
    return {
        "VALIDATE": "VALIDATION_FINDING",
        "PARSE": "PARSER_GAP",
        "ROUND_TRIP": "ROUND_TRIP_DIFFERENCE",
    }.get(name, "STRUCTURE_COMPILATION_FAILED")


@dataclass(frozen=True)
class MatrixRow:
    message_type: str
    release: str
    lane: str
    structure_source: str
    readiness: str
    generatable: bool
    gates: Gates
    blockers: tuple[str, ...]
    rules: dict[str, int]

    @property
    def category(self) -> str:
        return self.message_type[2]

    def gate(self, name: str) -> str:
        if not self.gates:
            return "yes" if self.generatable else "—"
        result = self.gates.get(name)
        if result is None:
            return "not reached"
        return "yes" if result.get("passed") else "no"

    @property
    def rule_fidelity(self) -> str:
        if not self.rules:
            return "—"
        return (
            f"{self.rules['exact']} exact / {self.rules['partial']} partial / "
            f"{self.rules['unsupported']} unsupported"
        )

    @property
    def root_cause(self) -> str:
        if self.lane == "CONFIGURED":
            return "—"
        return root_cause(self.readiness, self.blockers, self.gates)


def _rule_index() -> dict[tuple[str, str], dict[str, int]]:
    """``(message, release) -> {rules, exact, partial, unsupported}`` from the committed
    corpus evidence index; empty when the index is absent."""
    import json

    path = PROJECT_ROOT / "backend" / "tests" / "fixtures" / "mt_mrg"
    path = path / "sr2026-corpus-evidence.json"
    if not path.exists():
        return {}
    payload = json.loads(path.read_text(encoding="utf-8"))
    found: dict[tuple[str, str], dict[str, int]] = {}
    for guide in payload.get("guides", []):
        counts = {"rules": 0, "exact": 0, "partial": 0, "unsupported": 0}
        for rule in guide.get("networkValidatedRules", []):
            counts["rules"] += 1
            disposition = rule.get("disposition")
            if disposition == "EXACT":
                counts["exact"] += 1
            elif disposition == "PARTIAL_WEAKER_THAN_SOURCE":
                counts["partial"] += 1
            else:
                counts["unsupported"] += 1
        found[(str(guide["messageType"]), str(guide["release"]))] = counts
    return found


def _mt_rows() -> list[MatrixRow]:
    """One row per MT catalogue entry — configured first, then every preview structure."""
    from app.knowledge_base.preview import preview_registries
    from app.studio.catalogue import build_catalogue

    rules = _rule_index()
    rows: list[MatrixRow] = []
    for entry in build_catalogue().messages:
        if entry.format.value != "MT":
            continue
        release = entry.release or "PUBLIC_UHB_REVIEW_2026_08_05"
        gates: Gates = {}
        structure_source = "configured YAML"
        if entry.lane.value == "KNOWLEDGE_PREVIEW":
            status = preview_registries().structures.get(("MT", entry.message_type, release))
            if status is not None:
                gates = status.gates
                structure_source = status.structure_source
        common_group = f"MTn{entry.message_type[3:]}"
        rows.append(
            MatrixRow(
                message_type=entry.message_type,
                release=release,
                lane=entry.lane.value,
                structure_source=structure_source,
                readiness=entry.readiness.value if entry.readiness else "CONFIGURED",
                generatable=bool(entry.generatable),
                gates=gates,
                blockers=tuple(entry.blockers or ()),
                rules=rules.get((entry.message_type, release))
                or rules.get((common_group, release))
                or {},
            )
        )
    return rows


def render_generation_coverage() -> str:
    lines = [
        "# Universal MT generation coverage",
        "",
        "Generated by `python -m app.knowledge_base reports`. One row per MT catalogue entry — "
        "the 16 configured messages and every structure the knowledge base compiled, per "
        "release. *Generation* is the six-gate verdict (load, sample, validate, compose, parse, "
        "round trip); Excel and JSON follow from it, because every generation-ready structure "
        "is served by the same template builder and the same `/api/v1` endpoints. The "
        "semantic columns come from the committed corpus evidence index "
        "(`backend/tests/fixtures/mt_mrg/sr2026-corpus-evidence.json`); every rule there is "
        "`REVIEW_REQUIRED` and none is active.",
        "",
    ]
    from app.knowledge_base.service import knowledge_service

    if not knowledge_service.indexed:
        lines.append(NOT_AVAILABLE)
        return _normalise(lines)
    rows = _mt_rows()
    preview = [row for row in rows if row.lane != "CONFIGURED"]
    by_release = Counter((row.release, row.readiness) for row in preview)
    types = {row.message_type for row in rows}
    ready_types = {row.message_type for row in rows if row.generatable}
    ready = sum(1 for row in rows if row.generatable)
    lines += [
        "## Summary",
        "",
        f"- MT catalogue entries: {len(rows)} ({len(rows) - len(preview)} configured, "
        f"{len(preview)} knowledge-preview)",
        f"- Generation-ready entries: {ready}",
        f"- Blocked entries: {len(rows) - ready} "
        "(see [mt-generation-blockers.md](mt-generation-blockers.md))",
        f"- Distinct MT message types: {len(types)}; with at least one generation-ready "
        f"structure: {len(ready_types)}",
        "",
        "| Release | Readiness | Entries |",
        "|---|---|---:|",
    ]
    for (release, readiness), count in sorted(by_release.items()):
        lines.append(f"| {release} | {readiness} | {count} |")
    lines += [
        "",
        "## Matrix",
        "",
        "| MT | Cat | Release | Structure source | Generation | Sample | Parser | Round trip | "
        "Excel | JSON | Semantic source | Rules | Rule fidelity | Blockers |",
        "|---|---|---|---|---|---|---|---|---|---|---|---:|---|---|",
    ]
    for row in rows:
        yes_no = "yes" if row.generatable else "no"
        lines.append(
            f"| {row.message_type} | {row.category} | {row.release} | {row.structure_source} | "
            f"{row.readiness} | {row.gate('SAMPLE')} | {row.gate('PARSE')} | "
            f"{row.gate('ROUND_TRIP')} | {yes_no} | {yes_no} | "
            f"{'SR2026 MRG' if row.rules else '—'} | {row.rules.get('rules', 0)} | "
            f"{row.rule_fidelity} | {', '.join(row.blockers) or '—'} |"
        )
    return _normalise(lines)


def render_generation_blockers() -> str:
    lines = [
        "# MT generation blockers",
        "",
        "Generated by `python -m app.knowledge_base reports`. Every MT catalogue entry that is "
        "not generation-ready, grouped by root cause — the generic defect or the missing "
        "evidence behind it — with the gate that stopped it. A group marked *missing "
        "evidence* is not a defect to fix in code: the knowledge base holds nothing that "
        "would let the structure be compiled without inventing it.",
        "",
    ]
    from app.knowledge_base.service import knowledge_service

    if not knowledge_service.indexed:
        lines.append(NOT_AVAILABLE)
        return _normalise(lines)
    rows = [row for row in _mt_rows() if not row.generatable]
    groups: dict[str, list[MatrixRow]] = {}
    for row in rows:
        groups.setdefault(row.root_cause, []).append(row)
    ordered = sorted(groups.items(), key=lambda item: (-len(item[1]), item[0]))
    explanations = {code: (what, status) for code, what, status in ROOT_CAUSES}
    lines += [
        "## Summary",
        "",
        f"- Blocked entries: {len(rows)}",
        "",
        "| Root cause | Entries | What it is | Status |",
        "|---|---:|---|---|",
    ]
    for code, members in ordered:
        what, status = explanations.get(code, ("", ""))
        lines.append(f"| {code} | {len(members)} | {what} | {status} |")
    for code, members in ordered:
        lines += [
            "",
            f"## {code}",
            "",
            "| MT | Release | Structure source | First failed gate | Detail |",
            "|---|---|---|---|---|",
        ]
        for row in members:
            failed = _first_failed(row.gates) or ("—", ", ".join(row.blockers))
            detail = failed[1][:140].replace("|", "/")
            lines.append(
                f"| {row.message_type} | {row.release} | {row.structure_source} | "
                f"{failed[0]} | {detail} |"
            )
    return _normalise(lines)


def rendered() -> dict[Path, str]:
    return {
        READINESS_DOC: render_readiness(),
        COVERAGE_DOC: render_coverage(),
        SAMPLE_DOC: render_sample_readiness(),
        GENERATION_DOC: render_generation_coverage(),
        BLOCKERS_DOC: render_generation_blockers(),
    }


def write_reports() -> list[Path]:
    DOCS.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for path, text in rendered().items():
        path.write_text(text, encoding="utf-8")
        written.append(path.relative_to(PROJECT_ROOT))
    return written


def stale_reports() -> list[Path]:
    stale: list[Path] = []
    for path, text in rendered().items():
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            stale.append(path.relative_to(PROJECT_ROOT))
    return stale
