"""The three generated knowledge documents.

Rendered from the local knowledge database and the preview registries — ids, hashes,
counts, pages and readiness, never source text. Deterministic: no timestamps, so two
renders of the same state are byte-identical. They are regenerated by the operator after a
sync (``make knowledge-reports-write``) and committed as derived metadata.
"""

from __future__ import annotations

from collections import Counter
from pathlib import Path

from app.config import PROJECT_ROOT, get_settings

DOCS = PROJECT_ROOT / "docs" / "generated"
READINESS_DOC = DOCS / "universal-message-readiness.md"
COVERAGE_DOC = DOCS / "knowledge-rag-coverage.md"
SAMPLE_DOC = DOCS / "ai-sample-readiness.md"

NOT_AVAILABLE = (
    "SOURCE_NOT_AVAILABLE: no knowledge database is present on this machine. Run "
    "`make knowledge-sync` with the operator's sources, then `make knowledge-reports-write`."
)


def _normalise(lines: list[str]) -> str:
    """One trailing newline, never a blank last line — `git diff --check` refuses one."""
    text = "\n".join(lines).rstrip("\n")
    return text + "\n"


def render_readiness() -> str:
    from app.knowledge_base.preview import preview_registries
    from app.knowledge_base.service import knowledge_service

    lines = [
        "# Universal message readiness",
        "",
        "Generated by `python -m app.knowledge_base reports`. The honest answer to *what can I "
        "test?*: one row per message and release the knowledge base knows, with what its "
        "structure rests on and exactly what blocks generation where it is blocked. "
        "Configured messages are listed first; they are unchanged by Phase 6.",
        "",
    ]
    if not knowledge_service.indexed:
        lines.append(NOT_AVAILABLE)
        return _normalise(lines)
    registries = preview_registries()
    sources = knowledge_service.source_counts()
    by_key: dict[tuple[str, str, str], dict[str, object]] = {}
    for (fmt, mt, release), status in registries.structures.items():
        by_key[(fmt, mt, release)] = {
            "structureSource": status.structure_source,
            "readiness": status.readiness.value,
            "blockers": ", ".join(status.blockers) or "—",
            "gates": "/".join(name for name, result in status.gates.items() if result.get("passed"))
            or "—",
            "sources": sources.get((fmt, mt, release), 0),
        }
    for key, count in sources.items():
        by_key.setdefault(
            key,
            {
                "structureSource": "—",
                "readiness": "KNOWLEDGE_ONLY",
                "blockers": "STRUCTURE_SOURCE_MISSING",
                "gates": "—",
                "sources": count,
            },
        )
    totals = Counter(str(item["readiness"]) for item in by_key.values())
    lines += [
        "## Summary",
        "",
        f"- Messages/releases discovered: {len(by_key)}",
        f"- Generation ready (knowledge-preview lane): {totals.get('GENERATION_READY', 0)}",
        f"- Structure verified, round trip not established: {totals.get('STRUCTURE_VERIFIED', 0)}",
        f"- Structure evidence available, generation not established: "
        f"{totals.get('STRUCTURE_AVAILABLE', 0)}",
        f"- Knowledge only: {totals.get('KNOWLEDGE_ONLY', 0)}",
        "",
        "`GENERATION_READY` means the pack loaded, a deterministic sample validated, composed, "
        "parsed back and re-composed identically (MX: and the source XSD accepted it). It does "
        "not mean complete semantic rules, SWIFT certification or conformance.",
        "",
        "## Configured lane (unchanged)",
        "",
    ]
    from app.specifications.registry import specification_registry
    from app.studio.mx.registry import mx_registry

    lines += [
        "| Format | Message | Release/version | Structure source | Rules | Status |",
        "|---|---|---|---|---|---|",
    ]
    for spec in specification_registry.list():
        lines.append(
            f"| MT | {spec.message_type} | {spec.standards_release} | configured YAML | "
            f"configured + reviewed packs | Configured & validated |"
        )
    for mx_spec in mx_registry.all_specs():
        lines.append(
            f"| MX | {mx_spec.message_type} | {mx_spec.version} | configured YAML | "
            f"configured + reviewed packs | Configured & validated |"
        )
    lines += [
        "",
        "## Knowledge-preview lane",
        "",
        "| Format | Message | Release/version | Source docs | Structure source | Readiness | "
        "Gates passed | Blocking reason |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for (fmt, mt, release), item in sorted(by_key.items()):
        lines.append(
            f"| {fmt} | {mt} | {release or '—'} | {item['sources']} | {item['structureSource']} | "
            f"{item['readiness']} | {item['gates']} | {item['blockers']} |"
        )
    lines += [
        "",
        "Rules status for every preview row: NOT_ESTABLISHED (candidate packs, where a guide "
        "exists, remain REVIEW_REQUIRED). RAG indexed: every row with a source document. "
        "Embedding indexed: see knowledge-rag-coverage.md. Excel and JSON API: available for "
        "every GENERATION_READY row through `lane=KNOWLEDGE_PREVIEW`.",
    ]
    return _normalise(lines)


def render_coverage() -> str:
    from app.knowledge_base.service import knowledge_service

    lines = [
        "# Knowledge RAG coverage",
        "",
        "Generated by `python -m app.knowledge_base reports`. Sources, segments and embedding "
        "state of the local knowledge base. Checksums identify documents; no text is quoted.",
        "",
    ]
    if not knowledge_service.indexed:
        lines.append(NOT_AVAILABLE)
        return _normalise(lines)
    sources = knowledge_service.sources()
    live = [s for s in sources if not s.deleted]
    counts = knowledge_service.database.counts()
    last_run = knowledge_service.database.last_run() or {}
    stats = last_run.get("stats", {}) if isinstance(last_run, dict) else {}
    by_state = Counter(s.ingestion_state.value for s in live)
    blocked = sum(1 for s in live if s.embedding_policy.value == "BLOCKED")
    releases = sorted({s.release for s in live if s.release})
    messages = sorted({s.message_version or s.message_type or "" for s in live if s.message_type})
    checksums = Counter(s.checksum for s in sources)
    duplicates = sum(1 for _c, n in checksums.items() if n > 1)
    paths_per_source = sum(len(s.relative_paths) for s in live) - len(live)
    lines += [
        "## Totals",
        "",
        f"- Sources discovered: {len(sources)} (deleted/tombstoned: {len(sources) - len(live)})",
        f"- Sources indexed: {len(live)}",
        f"- Pages: {sum(s.page_count or 0 for s in live)}",
        f"- Segments: {counts.get('segments', 0)}",
        f"- Messages: {len(messages)}",
        f"- Releases: {', '.join(releases) or '—'}",
        f"- FTS indexed segments: {counts.get('segments', 0)}",
        f"- Embedding indexed segments: {counts.get('embeddings', 0)}",
        f"- Sources embedding-blocked by policy: {blocked} of {len(live)}",
        f"- Failed: {by_state.get('FAILED', 0)} · Unsupported: {by_state.get('UNSUPPORTED', 0)}",
        f"- Duplicate sources (same bytes, several paths): {duplicates + max(0, paths_per_source)}",
        f"- Last run — chunks reused: {stats.get('segmentsReused', 0)}, embedding cache hits: "
        f"{stats.get('embeddingCacheHits', 0)}, embedding requests: "
        f"{stats.get('embeddingRequests', 0)}, requests avoided: "
        f"{stats.get('embeddingRequestsAvoided', 0)}",
        "",
        "## Sources",
        "",
        "| Source id | Format | Message | Release/version | Type | Pages | Segments | "
        "Embedded | Embedding policy | State | Checksum |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for s in sorted(live, key=lambda item: item.source_id):
        lines.append(
            f"| {s.source_id} | {s.format.value} | {s.message_type or '—'} | "
            f"{s.message_version or s.release or '—'} | {s.document_type.value} | "
            f"{s.page_count or '—'} | {s.segment_count} | {s.embedded_count} | "
            f"{s.embedding_policy.value} | {s.ingestion_state.value} | "
            f"sha256:{s.checksum[:16]}… |"
        )
    return _normalise(lines)


def render_sample_readiness() -> str:
    from app.knowledge_base.preview import preview_registries
    from app.knowledge_base.service import knowledge_service
    from app.studio.catalogue import message_spec
    from app.studio.models import Lane, MessageFormat, Presence

    settings = get_settings()
    lines = [
        "# AI sample readiness",
        "",
        "Generated by `python -m app.knowledge_base reports`. For every generation-ready "
        "message: which sample types are structurally meaningful and whether a validated AI "
        "sample is already cached. Samples are generated lazily on first request and cached; "
        "nothing here was generated in bulk.",
        "",
        "Statuses: CACHE_READY (validated sample cached, 0 model calls on next request), "
        "AI_READY (provider configured, first request will generate), DETERMINISTIC_FALLBACK "
        "(no provider; the deterministic sample serves), N/A (variant not offered).",
        "",
    ]
    if not knowledge_service.indexed:
        lines.append(NOT_AVAILABLE)
        return _normalise(lines)
    provider = settings.structured_ai_provider_effective
    registries = preview_registries()
    rows: list[tuple[str, str, str, str, str, str, str]] = []

    def status_for(fmt: str, mt: str, release: str, variant: str, offered: bool) -> str:
        if not offered:
            return "N/A"
        if knowledge_service.sample_cached(fmt, mt, release):
            return "CACHE_READY"
        return "AI_READY" if provider != "disabled" else "DETERMINISTIC_FALLBACK"

    from app.specifications.registry import specification_registry
    from app.studio.mx.registry import mx_registry

    def variants_of(spec_fields: list[object]) -> tuple[bool, bool, bool]:
        mandatory = sum(
            1 for f in spec_fields if getattr(f, "presence", None) is Presence.MANDATORY
        )
        total = len(spec_fields)
        return True, mandatory < total, mandatory < total <= 500

    for spec in specification_registry.list():
        projected = message_spec(MessageFormat.MT, spec.message_type)
        minimal, typical, full = variants_of(list(projected.fields))
        rows.append(
            (
                "MT",
                spec.message_type,
                "configured",
                "CONFIGURED",
                status_for("MT", spec.message_type, "", "MINIMAL", minimal),
                status_for("MT", spec.message_type, "", "TYPICAL", typical),
                status_for("MT", spec.message_type, "", "FULL", full),
            )
        )
    for mx_spec in mx_registry.all_specs():
        projected = message_spec(MessageFormat.MX, mx_spec.version)
        minimal, typical, full = variants_of(list(projected.fields))
        rows.append(
            (
                "MX",
                mx_spec.message_type,
                mx_spec.version,
                "CONFIGURED",
                status_for("MX", mx_spec.message_type, mx_spec.version, "MINIMAL", minimal),
                status_for("MX", mx_spec.message_type, mx_spec.version, "TYPICAL", typical),
                status_for("MX", mx_spec.message_type, mx_spec.version, "FULL", full),
            )
        )
    for (fmt, mt, release), status in sorted(registries.structures.items()):
        if not status.generation_ready:
            continue
        try:
            projected = message_spec(
                MessageFormat(fmt),
                mt if fmt == "MT" else release,
                Lane.KNOWLEDGE_PREVIEW,
                release if fmt == "MT" else None,
            )
        except (LookupError, KeyError):
            continue
        minimal, _typical, full = variants_of(list(projected.fields))
        rows.append(
            (
                fmt,
                mt,
                release,
                "KNOWLEDGE_PREVIEW",
                status_for(fmt, mt, release, "MINIMAL", minimal),
                "N/A",
                status_for(fmt, mt, release, "FULL", full),
            )
        )
    cached = sum(1 for r in rows if "CACHE_READY" in r[4:])
    lines += [
        f"- Generation-ready messages listed: {len(rows)}",
        f"- With a cached validated AI sample: {cached}",
        f"- AI provider configured: {'yes' if provider != 'disabled' else 'no'} "
        f"({provider if provider != 'disabled' else 'deterministic fallback only'})",
        "",
        "| Format | Message | Release/version | Lane | Minimal | Typical | Full |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return _normalise(lines)


def rendered() -> dict[Path, str]:
    return {
        READINESS_DOC: render_readiness(),
        COVERAGE_DOC: render_coverage(),
        SAMPLE_DOC: render_sample_readiness(),
    }


def write_reports() -> list[Path]:
    DOCS.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for path, text in rendered().items():
        path.write_text(text, encoding="utf-8")
        written.append(path.relative_to(PROJECT_ROOT))
    return written


def stale_reports() -> list[Path]:
    stale: list[Path] = []
    for path, text in rendered().items():
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            stale.append(path.relative_to(PROJECT_ROOT))
    return stale
