"""compile(): source schema → validated pack text, with every finding attached."""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from pathlib import Path

from app.spec_engine import COMPILER_VERSION
from app.spec_engine.diagnostics import (
    CompilationError,
    CompilerFinding,
    FindingLog,
)
from app.spec_engine.mapper import map_message
from app.spec_engine.xsd_loader import load_schema_set
from app.spec_engine.xsd_reader import SchemaReader
from app.studio.mx.models import MxMessageSpec


@dataclass
class CompiledPack:
    message_type: str
    version: str
    yaml_text: str
    spec: MxMessageSpec
    source_checksum: str
    findings: list[CompilerFinding] = field(default_factory=list)

    @property
    def file_name(self) -> str:
        return f"{self.version}.yaml"


def compile_schema(
    entry: Path,
    *,
    bundle_root: Path | None = None,
    source_type: str = "OPERATOR_SUPPLIED_XSD",
    root_name: str | None = None,
) -> CompiledPack:
    """Compile one message schema (plus its local bundle) into a specification pack."""
    schema_set = load_schema_set(entry, bundle_root)

    checksum = "sha256:" + hashlib.sha256(entry.read_bytes()).hexdigest()

    reader_log = FindingLog()
    namespace = schema_set.entry_namespace()
    ir = SchemaReader(schema_set, reader_log).read(namespace)
    if reader_log.blocked:
        raise CompilationError(reader_log.findings)

    spec_dict, mapping_log = map_message(
        ir,
        source_type=source_type,
        source_reference=f"COMPILED-FROM-{entry.name.upper()}",
        source_location=entry.name,
        source_checksum=checksum,
        root_name=root_name,
    )
    findings = [*reader_log.findings, *mapping_log.findings]
    if mapping_log.blocked:
        raise CompilationError(findings)

    from app.spec_engine.emit import emit_pack

    header = (
        f"Generated by {COMPILER_VERSION} from {entry.name} ({checksum}).\n"
        "Structure follows the source schema; do not edit by hand — recompile instead.\n"
        "Business rules, market practice and client rules are NOT established by this file."
    )
    yaml_text = emit_pack(spec_dict, header_comment=header)
    spec = MxMessageSpec.model_validate(spec_dict)
    return CompiledPack(
        message_type=spec.message_type,
        version=spec.version,
        yaml_text=yaml_text,
        spec=spec,
        source_checksum=checksum,
        findings=findings,
    )
